version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: siapajar-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER:-siapajar}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-siapajar_secret}
      POSTGRES_DB: ${DB_DATABASE:-siapajar}
    volumes:
      - siapajar-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-siapajar} -d ${DB_DATABASE:-siapajar}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: siapajar-redis
    ports:
      - '6379:6379'
    volumes:
      - siapajar-redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  siapajar-pgdata:
  siapajar-redisdata:
