version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pajar-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER:-pajar}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pajar_secret}
      POSTGRES_DB: ${DB_DATABASE:-pajar}
    volumes:
      - pajar-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-pajar} -d ${DB_DATABASE:-pajar}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pajar-redis
    ports:
      - '6379:6379'
    volumes:
      - pajar-redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pajar-pgdata:
  pajar-redisdata:
