/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminAcademicYears: () => import('#controllers/admin_academic_years_controller'),
  AdminAiSettings: () => import('#controllers/admin_ai_settings_controller'),
  AdminPackages: () => import('#controllers/admin_packages_controller'),
  AdminUsers: () => import('#controllers/admin_users_controller'),
  AnnualPlans: () => import('#controllers/annual_plans_controller'),
  Assessments: () => import('#controllers/assessments_controller'),
  Classes: () => import('#controllers/classes_controller'),
  DailyLessonPlans: () => import('#controllers/daily_lesson_plans_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Exams: () => import('#controllers/exams_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Onboarding: () => import('#controllers/onboarding_controller'),
  PaudAssessments: () => import('#controllers/paud_assessments_controller'),
  SemesterPlans: () => import('#controllers/semester_plans_controller'),
  Session: () => import('#controllers/session_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Subjects: () => import('#controllers/subjects_controller'),
  TeachingModules: () => import('#controllers/teaching_modules_controller'),
  WeeklyLessonPlans: () => import('#controllers/weekly_lesson_plans_controller'),
}
