/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AcademicYearSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = AcademicYearSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AiSettingSchema extends BaseModel {
  static $columns = ['apiKey', 'baseUrl', 'createdAt', 'id', 'model', 'provider', 'updatedAt'] as const
  $columns = AiSettingSchema.$columns
  @column()
  declare apiKey: string | null
  @column()
  declare baseUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string | null
  @column()
  declare provider: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AnnualPlanSchema extends BaseModel {
  static $columns = ['academicYearId', 'content', 'createdAt', 'id', 'subject', 'updatedAt', 'userId'] as const
  $columns = AnnualPlanSchema.$columns
  @column()
  declare academicYearId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AssessmentSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'date', 'id', 'learningObjective', 'semesterId', 'subject', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = AssessmentSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare learningObjective: string | null
  @column()
  declare semesterId: number | null
  @column()
  declare subject: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ClassSchema extends BaseModel {
  static $columns = ['academicYearId', 'createdAt', 'gradeLevel', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = ClassSchema.$columns
  @column()
  declare academicYearId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gradeLevel: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class DailyLessonPlanSchema extends BaseModel {
  static $columns = ['classId', 'content', 'createdAt', 'date', 'id', 'status', 'updatedAt', 'userId', 'weeklyLessonPlanId'] as const
  $columns = DailyLessonPlanSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare weeklyLessonPlanId: number | null
}

export class ExamSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'id', 'questions', 'status', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = ExamSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare questions: any
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PackageSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'displayName', 'features', 'id', 'isActive', 'name', 'priceMonthly', 'priceYearly', 'sortOrder', 'updatedAt'] as const
  $columns = PackageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare displayName: string
  @column()
  declare features: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare priceMonthly: number
  @column()
  declare priceYearly: number | null
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaudAssessmentSchema extends BaseModel {
  static $columns = ['classId', 'content', 'createdAt', 'date', 'id', 'semesterId', 'studentId', 'type', 'updatedAt', 'userId'] as const
  $columns = PaudAssessmentSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare semesterId: number | null
  @column()
  declare studentId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SchoolSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'npsn', 'updatedAt'] as const
  $columns = SchoolSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare npsn: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScoreSchema extends BaseModel {
  static $columns = ['assessmentId', 'createdAt', 'id', 'note', 'studentId', 'updatedAt', 'value'] as const
  $columns = ScoreSchema.$columns
  @column()
  declare assessmentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class SemesterPlanSchema extends BaseModel {
  static $columns = ['classId', 'content', 'createdAt', 'id', 'semesterId', 'subject', 'updatedAt', 'userId'] as const
  $columns = SemesterPlanSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare semesterId: number
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SemesterSchema extends BaseModel {
  static $columns = ['academicYearId', 'createdAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = SemesterSchema.$columns
  @column()
  declare academicYearId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StudentSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'fullName', 'id', 'nis', 'nisn', 'updatedAt'] as const
  $columns = StudentSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nis: string
  @column()
  declare nisn: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubjectSchema extends BaseModel {
  static $columns = ['createdAt', 'educationLevel', 'gradeLevel', 'id', 'isActive', 'name', 'updatedAt', 'userId'] as const
  $columns = SubjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare educationLevel: string
  @column()
  declare gradeLevel: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TeachingModuleSchema extends BaseModel {
  static $columns = ['classId', 'content', 'createdAt', 'id', 'phase', 'status', 'subject', 'title', 'updatedAt', 'userId'] as const
  $columns = TeachingModuleSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phase: string
  @column()
  declare status: string | null
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'educationLevel', 'email', 'fullName', 'googleId', 'id', 'packageId', 'password', 'role', 'schoolId', 'schoolName', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare educationLevel: string | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare packageId: number | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare role: string
  @column()
  declare schoolId: number | null
  @column()
  declare schoolName: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WeeklyLessonPlanSchema extends BaseModel {
  static $columns = ['classId', 'content', 'createdAt', 'id', 'status', 'theme', 'updatedAt', 'userId', 'weekStartDate'] as const
  $columns = WeeklyLessonPlanSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column()
  declare theme: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column.date()
  declare weekStartDate: DateTime
}
