/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AcademicYearSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = AcademicYearSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AiJobSchema extends BaseModel {
  static $columns = [
    'attempts',
    'availableAt',
    'combo',
    'createdAt',
    'error',
    'finishedAt',
    'id',
    'jobKey',
    'payload',
    'result',
    'startedAt',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = AiJobSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime()
  declare availableAt: DateTime
  @column()
  declare combo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare error: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobKey: string
  @column()
  declare payload: any
  @column()
  declare result: any | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AiSettingSchema extends BaseModel {
  static $columns = [
    'apiKey',
    'authMode',
    'baseUrl',
    'createdAt',
    'gateway',
    'id',
    'model',
    'oauthAccessToken',
    'oauthEmail',
    'oauthExpiresAt',
    'oauthProjectId',
    'oauthRefreshToken',
    'provider',
    'reasoningEffort',
    'updatedAt',
  ] as const
  $columns = AiSettingSchema.$columns
  @column()
  declare apiKey: string | null
  @column()
  declare authMode: string
  @column()
  declare baseUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gateway: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare model: string | null
  @column()
  declare oauthAccessToken: string | null
  @column()
  declare oauthEmail: string | null
  @column.dateTime()
  declare oauthExpiresAt: DateTime | null
  @column()
  declare oauthProjectId: string | null
  @column()
  declare oauthRefreshToken: string | null
  @column()
  declare provider: string
  @column()
  declare reasoningEffort: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AnnualPlanSchema extends BaseModel {
  static $columns = [
    'academicYearId',
    'content',
    'createdAt',
    'id',
    'subject',
    'updatedAt',
    'userId',
  ] as const
  $columns = AnnualPlanSchema.$columns
  @column()
  declare academicYearId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AssessmentAttachmentSchema extends BaseModel {
  static $columns = [
    'assessmentId',
    'createdAt',
    'displayOrder',
    'id',
    'mimeType',
    'originalName',
    'size',
    'storedName',
    'updatedAt',
    'url',
    'userId',
  ] as const
  $columns = AssessmentAttachmentSchema.$columns
  @column()
  declare assessmentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare displayOrder: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare size: number
  @column()
  declare storedName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: number
}

export class AssessmentSchema extends BaseModel {
  static $columns = [
    'classId',
    'createdAt',
    'date',
    'id',
    'learningObjective',
    'semesterId',
    'subject',
    'title',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = AssessmentSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare learningObjective: string | null
  @column()
  declare semesterId: number | null
  @column()
  declare subject: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AuditLogSchema extends BaseModel {
  static $columns = [
    'action',
    'actorId',
    'createdAt',
    'entityId',
    'entityType',
    'id',
    'ipAddress',
    'metadata',
    'userAgent',
  ] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string | null
  @column()
  declare entityType: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any
  @column()
  declare userAgent: string | null
}

export class ClassSchema extends BaseModel {
  static $columns = [
    'academicYearId',
    'createdAt',
    'gradeLevel',
    'groupContext',
    'id',
    'name',
    'updatedAt',
    'userId',
  ] as const
  $columns = ClassSchema.$columns
  @column()
  declare academicYearId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gradeLevel: number
  @column()
  declare groupContext: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CurriculumCpSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'curriculumVersion',
    'description',
    'element',
    'id',
    'isOfficial',
    'phase',
    'title',
    'updatedAt',
  ] as const
  $columns = CurriculumCpSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare curriculumVersion: string
  @column()
  declare description: string
  @column()
  declare element: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isOfficial: boolean
  @column()
  declare phase: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DailyLessonPlanSchema extends BaseModel {
  static $columns = [
    'classId',
    'content',
    'createdAt',
    'date',
    'id',
    'status',
    'updatedAt',
    'userId',
    'weeklyLessonPlanId',
  ] as const
  $columns = DailyLessonPlanSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare weeklyLessonPlanId: number | null
}

export class DocumentWorkflowSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'documentId',
    'documentType',
    'id',
    'lastSavedAt',
    'status',
    'templateKey',
    'updatedAt',
    'userId',
    'version',
  ] as const
  $columns = DocumentWorkflowSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare documentId: number
  @column()
  declare documentType: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastSavedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare templateKey: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare version: number
}

export class ExamSchema extends BaseModel {
  static $columns = [
    'classId',
    'createdAt',
    'generationProgress',
    'generationStatus',
    'header',
    'id',
    'questions',
    'status',
    'title',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = ExamSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare generationProgress: any
  @column()
  declare generationStatus: string
  @column()
  declare header: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare questions: any
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class IktpIndicatorSchema extends BaseModel {
  static $columns = [
    'achievementCriteria',
    'createdAt',
    'description',
    'evidenceType',
    'id',
    'isActive',
    'learningObjectiveId',
    'updatedAt',
    'userId',
  ] as const
  $columns = IktpIndicatorSchema.$columns
  @column()
  declare achievementCriteria: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare evidenceType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare learningObjectiveId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class LearningObjectiveSchema extends BaseModel {
  static $columns = [
    'code',
    'cpId',
    'createdAt',
    'groupContext',
    'id',
    'isActive',
    'source',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = LearningObjectiveSchema.$columns
  @column()
  declare code: string
  @column()
  declare cpId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare groupContext: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare source: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class LearningSequenceSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'curriculumVersion',
    'educationLevel',
    'groupContext',
    'id',
    'items',
    'schoolId',
    'status',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = LearningSequenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare curriculumVersion: string
  @column()
  declare educationLevel: string
  @column()
  declare groupContext: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare items: any
  @column()
  declare schoolId: number | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class LkpdSchema extends BaseModel {
  static $columns = [
    'ageGroup',
    'classId',
    'content',
    'createdAt',
    'id',
    'institutionType',
    'status',
    'subtheme',
    'theme',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = LkpdSchema.$columns
  @column()
  declare ageGroup: string | null
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare institutionType: string | null
  @column()
  declare status: string | null
  @column()
  declare subtheme: string | null
  @column()
  declare theme: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class McpKeySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'keyHash',
    'label',
    'lastUsedAt',
    'revokedAt',
    'scopes',
    'updatedAt',
    'userId',
  ] as const
  $columns = McpKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column()
  declare label: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare scopes: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class MediaModuleSchema extends BaseModel {
  static $columns = [
    'classId',
    'createdAt',
    'id',
    'loosePartsGuide',
    'slides',
    'status',
    'subtheme',
    'theme',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = MediaModuleSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loosePartsGuide: any | null
  @column()
  declare slides: any
  @column()
  declare status: string | null
  @column()
  declare subtheme: string | null
  @column()
  declare theme: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PackageEntitlementSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'featureKey',
    'id',
    'isEnabled',
    'limitValue',
    'packageId',
    'updatedAt',
  ] as const
  $columns = PackageEntitlementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare featureKey: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isEnabled: boolean
  @column()
  declare limitValue: number | null
  @column()
  declare packageId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PackageSubscriptionSchema extends BaseModel {
  static $columns = [
    'billingCycle',
    'canceledAt',
    'createdAt',
    'endsAt',
    'id',
    'metadata',
    'packageId',
    'startsAt',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = PackageSubscriptionSchema.$columns
  @column()
  declare billingCycle: string
  @column.dateTime()
  declare canceledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any
  @column()
  declare packageId: number | null
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PackageSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'ctaLabel',
    'description',
    'displayName',
    'features',
    'id',
    'isActive',
    'isHighlighted',
    'name',
    'priceMonthly',
    'priceYearly',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = PackageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare ctaLabel: string | null
  @column()
  declare description: string | null
  @column()
  declare displayName: string
  @column()
  declare features: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isHighlighted: boolean
  @column()
  declare name: string
  @column()
  declare priceMonthly: number
  @column()
  declare priceYearly: number | null
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PaudAssessmentSchema extends BaseModel {
  static $columns = [
    'achievementStatus',
    'activity',
    'classId',
    'content',
    'createdAt',
    'date',
    'evidenceType',
    'evidenceUrl',
    'id',
    'iktpIndicatorId',
    'learningObjectiveId',
    'semesterId',
    'studentId',
    'teacherNote',
    'type',
    'updatedAt',
    'userId',
  ] as const
  $columns = PaudAssessmentSchema.$columns
  @column()
  declare achievementStatus: string | null
  @column()
  declare activity: string | null
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column()
  declare evidenceType: string | null
  @column()
  declare evidenceUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iktpIndicatorId: number | null
  @column()
  declare learningObjectiveId: number | null
  @column()
  declare semesterId: number | null
  @column()
  declare studentId: number
  @column()
  declare teacherNote: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReportNarrativeSchema extends BaseModel {
  static $columns = [
    'approvedAt',
    'classId',
    'content',
    'createdAt',
    'element',
    'id',
    'semesterId',
    'status',
    'studentId',
    'updatedAt',
    'userId',
  ] as const
  $columns = ReportNarrativeSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare classId: number
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare element: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare semesterId: number
  @column()
  declare status: string
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SchoolSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'npsn', 'updatedAt'] as const
  $columns = SchoolSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare npsn: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScoreSchema extends BaseModel {
  static $columns = [
    'assessmentId',
    'createdAt',
    'id',
    'note',
    'studentId',
    'updatedAt',
    'value',
  ] as const
  $columns = ScoreSchema.$columns
  @column()
  declare assessmentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare studentId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class SemesterPlanSchema extends BaseModel {
  static $columns = [
    'classId',
    'content',
    'createdAt',
    'id',
    'semesterId',
    'subject',
    'updatedAt',
    'userId',
  ] as const
  $columns = SemesterPlanSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare semesterId: number
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SemesterSchema extends BaseModel {
  static $columns = ['academicYearId', 'createdAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = SemesterSchema.$columns
  @column()
  declare academicYearId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StudentSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'fullName', 'id', 'nis', 'nisn', 'updatedAt'] as const
  $columns = StudentSchema.$columns
  @column()
  declare classId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nis: string
  @column()
  declare nisn: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubjectSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'educationLevel',
    'gradeLevel',
    'id',
    'isActive',
    'name',
    'updatedAt',
    'userId',
  ] as const
  $columns = SubjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare educationLevel: string
  @column()
  declare gradeLevel: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TeachingModuleSchema extends BaseModel {
  static $columns = [
    'classId',
    'content',
    'createdAt',
    'id',
    'phase',
    'status',
    'subject',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = TeachingModuleSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phase: string
  @column()
  declare status: string | null
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UsageEventSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'eventKey',
    'id',
    'metadata',
    'periodStart',
    'quantity',
    'reservationKey',
    'updatedAt',
    'userId',
  ] as const
  $columns = UsageEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventKey: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any
  @column.date()
  declare periodStart: DateTime
  @column()
  declare quantity: number
  @column()
  declare reservationKey: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'createdAt',
    'curriculumVersion',
    'defaultGroupContext',
    'educationLevel',
    'email',
    'fullName',
    'googleId',
    'id',
    'institutionType',
    'kopSurat',
    'packageId',
    'password',
    'role',
    'schoolId',
    'schoolName',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare curriculumVersion: string | null
  @column()
  declare defaultGroupContext: string | null
  @column()
  declare educationLevel: string | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare institutionType: string | null
  @column()
  declare kopSurat: any | null
  @column()
  declare packageId: number | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare role: string
  @column()
  declare schoolId: number | null
  @column()
  declare schoolName: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VisualAssetSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'error',
    'height',
    'id',
    'kind',
    'metadata',
    'mimeType',
    'model',
    'prompt',
    'promptHash',
    'provider',
    'schoolId',
    'source',
    'status',
    'storagePath',
    'updatedAt',
    'url',
    'userId',
    'viewBox',
    'width',
  ] as const
  $columns = VisualAssetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare error: string | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare metadata: any
  @column()
  declare mimeType: string
  @column()
  declare model: string | null
  @column()
  declare prompt: string | null
  @column()
  declare promptHash: string | null
  @column()
  declare provider: string | null
  @column()
  declare schoolId: number | null
  @column()
  declare source: string
  @column()
  declare status: string
  @column()
  declare storagePath: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
  @column()
  declare userId: number
  @column()
  declare viewBox: string | null
  @column()
  declare width: number | null
}

export class WeeklyLessonPlanSchema extends BaseModel {
  static $columns = [
    'classId',
    'content',
    'createdAt',
    'id',
    'status',
    'theme',
    'updatedAt',
    'userId',
    'weekStartDate',
  ] as const
  $columns = WeeklyLessonPlanSchema.$columns
  @column()
  declare classId: number
  @column()
  declare content: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column()
  declare theme: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column.date()
  declare weekStartDate: DateTime
}
