/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'api.auth.login': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['api.auth.login']['types'],
  },
  'api.auth.logout': {
    methods: ["POST"],
    pattern: '/api/v1/auth/logout',
    tokens: [{"old":"/api/v1/auth/logout","type":0,"val":"api","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['api.auth.logout']['types'],
  },
  'api.auth.google.redirect': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/google/redirect',
    tokens: [{"old":"/api/v1/auth/google/redirect","type":0,"val":"api","end":""},{"old":"/api/v1/auth/google/redirect","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/google/redirect","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/google/redirect","type":0,"val":"google","end":""},{"old":"/api/v1/auth/google/redirect","type":0,"val":"redirect","end":""}],
    types: placeholder as Registry['api.auth.google.redirect']['types'],
  },
  'api.auth.google.callback': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/google/callback',
    tokens: [{"old":"/api/v1/auth/google/callback","type":0,"val":"api","end":""},{"old":"/api/v1/auth/google/callback","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/google/callback","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/google/callback","type":0,"val":"google","end":""},{"old":"/api/v1/auth/google/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['api.auth.google.callback']['types'],
  },
  'api.classes.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/classes',
    tokens: [{"old":"/api/v1/classes","type":0,"val":"api","end":""},{"old":"/api/v1/classes","type":0,"val":"v1","end":""},{"old":"/api/v1/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['api.classes.index']['types'],
  },
  'api.classes.students': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/classes/:id/students',
    tokens: [{"old":"/api/v1/classes/:id/students","type":0,"val":"api","end":""},{"old":"/api/v1/classes/:id/students","type":0,"val":"v1","end":""},{"old":"/api/v1/classes/:id/students","type":0,"val":"classes","end":""},{"old":"/api/v1/classes/:id/students","type":1,"val":"id","end":""},{"old":"/api/v1/classes/:id/students","type":0,"val":"students","end":""}],
    types: placeholder as Registry['api.classes.students']['types'],
  },
  'api.classes.agenda': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/classes/:id/today-agenda',
    tokens: [{"old":"/api/v1/classes/:id/today-agenda","type":0,"val":"api","end":""},{"old":"/api/v1/classes/:id/today-agenda","type":0,"val":"v1","end":""},{"old":"/api/v1/classes/:id/today-agenda","type":0,"val":"classes","end":""},{"old":"/api/v1/classes/:id/today-agenda","type":1,"val":"id","end":""},{"old":"/api/v1/classes/:id/today-agenda","type":0,"val":"today-agenda","end":""}],
    types: placeholder as Registry['api.classes.agenda']['types'],
  },
  'api.attendances.quickSubmit': {
    methods: ["POST"],
    pattern: '/api/v1/attendances/quick-submit',
    tokens: [{"old":"/api/v1/attendances/quick-submit","type":0,"val":"api","end":""},{"old":"/api/v1/attendances/quick-submit","type":0,"val":"v1","end":""},{"old":"/api/v1/attendances/quick-submit","type":0,"val":"attendances","end":""},{"old":"/api/v1/attendances/quick-submit","type":0,"val":"quick-submit","end":""}],
    types: placeholder as Registry['api.attendances.quickSubmit']['types'],
  },
  'api.assessments.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/assessments',
    tokens: [{"old":"/api/v1/assessments","type":0,"val":"api","end":""},{"old":"/api/v1/assessments","type":0,"val":"v1","end":""},{"old":"/api/v1/assessments","type":0,"val":"assessments","end":""}],
    types: placeholder as Registry['api.assessments.index']['types'],
  },
  'api.students.timeline': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/students/:id/timeline',
    tokens: [{"old":"/api/v1/students/:id/timeline","type":0,"val":"api","end":""},{"old":"/api/v1/students/:id/timeline","type":0,"val":"v1","end":""},{"old":"/api/v1/students/:id/timeline","type":0,"val":"students","end":""},{"old":"/api/v1/students/:id/timeline","type":1,"val":"id","end":""},{"old":"/api/v1/students/:id/timeline","type":0,"val":"timeline","end":""}],
    types: placeholder as Registry['api.students.timeline']['types'],
  },
  'api.assessments.quickCapture': {
    methods: ["POST"],
    pattern: '/api/v1/assessments/quick-capture',
    tokens: [{"old":"/api/v1/assessments/quick-capture","type":0,"val":"api","end":""},{"old":"/api/v1/assessments/quick-capture","type":0,"val":"v1","end":""},{"old":"/api/v1/assessments/quick-capture","type":0,"val":"assessments","end":""},{"old":"/api/v1/assessments/quick-capture","type":0,"val":"quick-capture","end":""}],
    types: placeholder as Registry['api.assessments.quickCapture']['types'],
  },
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'health': {
    methods: ["GET","HEAD"],
    pattern: '/health',
    tokens: [{"old":"/health","type":0,"val":"health","end":""}],
    types: placeholder as Registry['health']['types'],
  },
  'privacy': {
    methods: ["GET","HEAD"],
    pattern: '/privacy',
    tokens: [{"old":"/privacy","type":0,"val":"privacy","end":""}],
    types: placeholder as Registry['privacy']['types'],
  },
  'terms': {
    methods: ["GET","HEAD"],
    pattern: '/terms',
    tokens: [{"old":"/terms","type":0,"val":"terms","end":""}],
    types: placeholder as Registry['terms']['types'],
  },
  'api.mayar.webhook': {
    methods: ["POST"],
    pattern: '/api/webhooks/mayar/:secret',
    tokens: [{"old":"/api/webhooks/mayar/:secret","type":0,"val":"api","end":""},{"old":"/api/webhooks/mayar/:secret","type":0,"val":"webhooks","end":""},{"old":"/api/webhooks/mayar/:secret","type":0,"val":"mayar","end":""},{"old":"/api/webhooks/mayar/:secret","type":1,"val":"secret","end":""}],
    types: placeholder as Registry['api.mayar.webhook']['types'],
  },
  'api.packages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/packages',
    tokens: [{"old":"/api/packages","type":0,"val":"api","end":""},{"old":"/api/packages","type":0,"val":"packages","end":""}],
    types: placeholder as Registry['api.packages.index']['types'],
  },
  'mcp.wellknown': {
    methods: ["GET","HEAD"],
    pattern: '/.well-known/mcp',
    tokens: [{"old":"/.well-known/mcp","type":0,"val":".well-known","end":""},{"old":"/.well-known/mcp","type":0,"val":"mcp","end":""}],
    types: placeholder as Registry['mcp.wellknown']['types'],
  },
  'mcp.handle': {
    methods: ["HEAD","OPTIONS","GET","POST","PUT","PATCH","DELETE"],
    pattern: '/mcp',
    tokens: [{"old":"/mcp","type":0,"val":"mcp","end":""}],
    types: placeholder as Registry['mcp.handle']['types'],
  },
  'coming-soon': {
    methods: ["GET","HEAD"],
    pattern: '/coming-soon',
    tokens: [{"old":"/coming-soon","type":0,"val":"coming-soon","end":""}],
    types: placeholder as Registry['coming-soon']['types'],
  },
  'new_account.create': {
    methods: ["GET","HEAD"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.create']['types'],
  },
  'new_account.store': {
    methods: ["POST"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.store']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'auth.google.redirect': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google/redirect',
    tokens: [{"old":"/auth/google/redirect","type":0,"val":"auth","end":""},{"old":"/auth/google/redirect","type":0,"val":"google","end":""},{"old":"/auth/google/redirect","type":0,"val":"redirect","end":""}],
    types: placeholder as Registry['auth.google.redirect']['types'],
  },
  'auth.google.callback': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google/callback',
    tokens: [{"old":"/auth/google/callback","type":0,"val":"auth","end":""},{"old":"/auth/google/callback","type":0,"val":"google","end":""},{"old":"/auth/google/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['auth.google.callback']['types'],
  },
  'email_verification.pending': {
    methods: ["GET","HEAD"],
    pattern: '/verify-email/pending',
    tokens: [{"old":"/verify-email/pending","type":0,"val":"verify-email","end":""},{"old":"/verify-email/pending","type":0,"val":"pending","end":""}],
    types: placeholder as Registry['email_verification.pending']['types'],
  },
  'email_verification.resend': {
    methods: ["POST"],
    pattern: '/verify-email/resend',
    tokens: [{"old":"/verify-email/resend","type":0,"val":"verify-email","end":""},{"old":"/verify-email/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['email_verification.resend']['types'],
  },
  'account.email_change': {
    methods: ["POST"],
    pattern: '/account/email-change',
    tokens: [{"old":"/account/email-change","type":0,"val":"account","end":""},{"old":"/account/email-change","type":0,"val":"email-change","end":""}],
    types: placeholder as Registry['account.email_change']['types'],
  },
  'free_benefit.claim.page': {
    methods: ["GET","HEAD"],
    pattern: '/claim-free-benefit',
    tokens: [{"old":"/claim-free-benefit","type":0,"val":"claim-free-benefit","end":""}],
    types: placeholder as Registry['free_benefit.claim.page']['types'],
  },
  'free_benefit.claim': {
    methods: ["POST"],
    pattern: '/claim-free-benefit',
    tokens: [{"old":"/claim-free-benefit","type":0,"val":"claim-free-benefit","end":""}],
    types: placeholder as Registry['free_benefit.claim']['types'],
  },
  'email_verification.verify': {
    methods: ["GET","HEAD"],
    pattern: '/verify-email/:token',
    tokens: [{"old":"/verify-email/:token","type":0,"val":"verify-email","end":""},{"old":"/verify-email/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['email_verification.verify']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
  'onboarding.index': {
    methods: ["GET","HEAD"],
    pattern: '/onboarding',
    tokens: [{"old":"/onboarding","type":0,"val":"onboarding","end":""}],
    types: placeholder as Registry['onboarding.index']['types'],
  },
  'onboarding.store': {
    methods: ["POST"],
    pattern: '/onboarding',
    tokens: [{"old":"/onboarding","type":0,"val":"onboarding","end":""}],
    types: placeholder as Registry['onboarding.store']['types'],
  },
  'dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard']['types'],
  },
  'panel.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel',
    tokens: [{"old":"/panel","type":0,"val":"panel","end":""}],
    types: placeholder as Registry['panel.index']['types'],
  },
  'panel.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/panel/dashboard',
    tokens: [{"old":"/panel/dashboard","type":0,"val":"panel","end":""},{"old":"/panel/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['panel.dashboard']['types'],
  },
  'panel.curriculum.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/curriculum',
    tokens: [{"old":"/panel/curriculum","type":0,"val":"panel","end":""},{"old":"/panel/curriculum","type":0,"val":"curriculum","end":""}],
    types: placeholder as Registry['panel.curriculum.index']['types'],
  },
  'panel.classes.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/classes',
    tokens: [{"old":"/panel/classes","type":0,"val":"panel","end":""},{"old":"/panel/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['panel.classes.index']['types'],
  },
  'panel.subjects.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/subjects',
    tokens: [{"old":"/panel/subjects","type":0,"val":"panel","end":""},{"old":"/panel/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['panel.subjects.index']['types'],
  },
  'panel.glossary.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/glossary',
    tokens: [{"old":"/panel/glossary","type":0,"val":"panel","end":""},{"old":"/panel/glossary","type":0,"val":"glossary","end":""}],
    types: placeholder as Registry['panel.glossary.index']['types'],
  },
  'panel.teaching-modules.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/teaching-modules',
    tokens: [{"old":"/panel/teaching-modules","type":0,"val":"panel","end":""},{"old":"/panel/teaching-modules","type":0,"val":"teaching-modules","end":""}],
    types: placeholder as Registry['panel.teaching-modules.index']['types'],
  },
  'panel.annual-plans.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/annual-plans',
    tokens: [{"old":"/panel/annual-plans","type":0,"val":"panel","end":""},{"old":"/panel/annual-plans","type":0,"val":"annual-plans","end":""}],
    types: placeholder as Registry['panel.annual-plans.index']['types'],
  },
  'panel.semester-plans.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/semester-plans',
    tokens: [{"old":"/panel/semester-plans","type":0,"val":"panel","end":""},{"old":"/panel/semester-plans","type":0,"val":"semester-plans","end":""}],
    types: placeholder as Registry['panel.semester-plans.index']['types'],
  },
  'panel.rppm.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/rppm',
    tokens: [{"old":"/panel/rppm","type":0,"val":"panel","end":""},{"old":"/panel/rppm","type":0,"val":"rppm","end":""}],
    types: placeholder as Registry['panel.rppm.index']['types'],
  },
  'panel.rpph.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/rpph',
    tokens: [{"old":"/panel/rpph","type":0,"val":"panel","end":""},{"old":"/panel/rpph","type":0,"val":"rpph","end":""}],
    types: placeholder as Registry['panel.rpph.index']['types'],
  },
  'panel.lkpd.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/lkpd',
    tokens: [{"old":"/panel/lkpd","type":0,"val":"panel","end":""},{"old":"/panel/lkpd","type":0,"val":"lkpd","end":""}],
    types: placeholder as Registry['panel.lkpd.index']['types'],
  },
  'panel.media-modules.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/media-modules',
    tokens: [{"old":"/panel/media-modules","type":0,"val":"panel","end":""},{"old":"/panel/media-modules","type":0,"val":"media-modules","end":""}],
    types: placeholder as Registry['panel.media-modules.index']['types'],
  },
  'panel.exams.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/exams',
    tokens: [{"old":"/panel/exams","type":0,"val":"panel","end":""},{"old":"/panel/exams","type":0,"val":"exams","end":""}],
    types: placeholder as Registry['panel.exams.index']['types'],
  },
  'panel.assessments.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/assessments',
    tokens: [{"old":"/panel/assessments","type":0,"val":"panel","end":""},{"old":"/panel/assessments","type":0,"val":"assessments","end":""}],
    types: placeholder as Registry['panel.assessments.index']['types'],
  },
  'panel.paud-assessments.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/paud-assessments',
    tokens: [{"old":"/panel/paud-assessments","type":0,"val":"panel","end":""},{"old":"/panel/paud-assessments","type":0,"val":"paud-assessments","end":""}],
    types: placeholder as Registry['panel.paud-assessments.index']['types'],
  },
  'panel.report-cards.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/report-cards',
    tokens: [{"old":"/panel/report-cards","type":0,"val":"panel","end":""},{"old":"/panel/report-cards","type":0,"val":"report-cards","end":""}],
    types: placeholder as Registry['panel.report-cards.index']['types'],
  },
  'panel.jurnal.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/jurnal',
    tokens: [{"old":"/panel/jurnal","type":0,"val":"panel","end":""},{"old":"/panel/jurnal","type":0,"val":"jurnal","end":""}],
    types: placeholder as Registry['panel.jurnal.index']['types'],
  },
  'panel.kokurikuler.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/kokurikuler',
    tokens: [{"old":"/panel/kokurikuler","type":0,"val":"panel","end":""},{"old":"/panel/kokurikuler","type":0,"val":"kokurikuler","end":""}],
    types: placeholder as Registry['panel.kokurikuler.index']['types'],
  },
  'panel.katrol.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/katrol',
    tokens: [{"old":"/panel/katrol","type":0,"val":"panel","end":""},{"old":"/panel/katrol","type":0,"val":"katrol","end":""}],
    types: placeholder as Registry['panel.katrol.index']['types'],
  },
  'panel.account.package': {
    methods: ["GET","HEAD"],
    pattern: '/panel/my-package',
    tokens: [{"old":"/panel/my-package","type":0,"val":"panel","end":""},{"old":"/panel/my-package","type":0,"val":"my-package","end":""}],
    types: placeholder as Registry['panel.account.package']['types'],
  },
  'panel.settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/panel/settings',
    tokens: [{"old":"/panel/settings","type":0,"val":"panel","end":""},{"old":"/panel/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['panel.settings.index']['types'],
  },
  'billing.index': {
    methods: ["GET","HEAD"],
    pattern: '/billing',
    tokens: [{"old":"/billing","type":0,"val":"billing","end":""}],
    types: placeholder as Registry['billing.index']['types'],
  },
  'api.mayar.checkout': {
    methods: ["POST"],
    pattern: '/api/topup/mayar',
    tokens: [{"old":"/api/topup/mayar","type":0,"val":"api","end":""},{"old":"/api/topup/mayar","type":0,"val":"topup","end":""},{"old":"/api/topup/mayar","type":0,"val":"mayar","end":""}],
    types: placeholder as Registry['api.mayar.checkout']['types'],
  },
  'api.mayar.status': {
    methods: ["GET","HEAD"],
    pattern: '/api/topup/invoices/:invoiceNo',
    tokens: [{"old":"/api/topup/invoices/:invoiceNo","type":0,"val":"api","end":""},{"old":"/api/topup/invoices/:invoiceNo","type":0,"val":"topup","end":""},{"old":"/api/topup/invoices/:invoiceNo","type":0,"val":"invoices","end":""},{"old":"/api/topup/invoices/:invoiceNo","type":1,"val":"invoiceNo","end":""}],
    types: placeholder as Registry['api.mayar.status']['types'],
  },
  'account.package': {
    methods: ["GET","HEAD"],
    pattern: '/my-package',
    tokens: [{"old":"/my-package","type":0,"val":"my-package","end":""}],
    types: placeholder as Registry['account.package']['types'],
  },
  'account.usage': {
    methods: ["GET","HEAD"],
    pattern: '/usage',
    tokens: [{"old":"/usage","type":0,"val":"usage","end":""}],
    types: placeholder as Registry['account.usage']['types'],
  },
  'account.subscriptions': {
    methods: ["GET","HEAD"],
    pattern: '/subscriptions',
    tokens: [{"old":"/subscriptions","type":0,"val":"subscriptions","end":""}],
    types: placeholder as Registry['account.subscriptions']['types'],
  },
  'express.modulAjar': {
    methods: ["GET","HEAD"],
    pattern: '/modul-ajar',
    tokens: [{"old":"/modul-ajar","type":0,"val":"modul-ajar","end":""}],
    types: placeholder as Registry['express.modulAjar']['types'],
  },
  'lkpd.index': {
    methods: ["GET","HEAD"],
    pattern: '/lkpd',
    tokens: [{"old":"/lkpd","type":0,"val":"lkpd","end":""}],
    types: placeholder as Registry['lkpd.index']['types'],
  },
  'express.soal': {
    methods: ["GET","HEAD"],
    pattern: '/soal',
    tokens: [{"old":"/soal","type":0,"val":"soal","end":""}],
    types: placeholder as Registry['express.soal']['types'],
  },
  'express.protaPromes': {
    methods: ["GET","HEAD"],
    pattern: '/prota-promes',
    tokens: [{"old":"/prota-promes","type":0,"val":"prota-promes","end":""}],
    types: placeholder as Registry['express.protaPromes']['types'],
  },
  'express.rapor': {
    methods: ["GET","HEAD"],
    pattern: '/rapor',
    tokens: [{"old":"/rapor","type":0,"val":"rapor","end":""}],
    types: placeholder as Registry['express.rapor']['types'],
  },
  'express.katrol': {
    methods: ["GET","HEAD"],
    pattern: '/katrol',
    tokens: [{"old":"/katrol","type":0,"val":"katrol","end":""}],
    types: placeholder as Registry['express.katrol']['types'],
  },
  'api.express.katrol.generate': {
    methods: ["POST"],
    pattern: '/api/express/katrol/generate',
    tokens: [{"old":"/api/express/katrol/generate","type":0,"val":"api","end":""},{"old":"/api/express/katrol/generate","type":0,"val":"express","end":""},{"old":"/api/express/katrol/generate","type":0,"val":"katrol","end":""},{"old":"/api/express/katrol/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['api.express.katrol.generate']['types'],
  },
  'express.jurnal': {
    methods: ["GET","HEAD"],
    pattern: '/jurnal',
    tokens: [{"old":"/jurnal","type":0,"val":"jurnal","end":""}],
    types: placeholder as Registry['express.jurnal']['types'],
  },
  'api.express.jurnal.generate': {
    methods: ["POST"],
    pattern: '/api/express/jurnal/generate',
    tokens: [{"old":"/api/express/jurnal/generate","type":0,"val":"api","end":""},{"old":"/api/express/jurnal/generate","type":0,"val":"express","end":""},{"old":"/api/express/jurnal/generate","type":0,"val":"jurnal","end":""},{"old":"/api/express/jurnal/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['api.express.jurnal.generate']['types'],
  },
  'express.kokurikuler': {
    methods: ["GET","HEAD"],
    pattern: '/kokurikuler',
    tokens: [{"old":"/kokurikuler","type":0,"val":"kokurikuler","end":""}],
    types: placeholder as Registry['express.kokurikuler']['types'],
  },
  'api.express.kokurikuler.generate': {
    methods: ["POST"],
    pattern: '/api/express/kokurikuler/generate',
    tokens: [{"old":"/api/express/kokurikuler/generate","type":0,"val":"api","end":""},{"old":"/api/express/kokurikuler/generate","type":0,"val":"express","end":""},{"old":"/api/express/kokurikuler/generate","type":0,"val":"kokurikuler","end":""},{"old":"/api/express/kokurikuler/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['api.express.kokurikuler.generate']['types'],
  },
  'panel.legacy.kurikulum': {
    methods: ["GET","HEAD"],
    pattern: '/panel/kurikulum',
    tokens: [{"old":"/panel/kurikulum","type":0,"val":"panel","end":""},{"old":"/panel/kurikulum","type":0,"val":"kurikulum","end":""}],
    types: placeholder as Registry['panel.legacy.kurikulum']['types'],
  },
  'panel.legacy.kelas': {
    methods: ["GET","HEAD"],
    pattern: '/panel/kelas',
    tokens: [{"old":"/panel/kelas","type":0,"val":"panel","end":""},{"old":"/panel/kelas","type":0,"val":"kelas","end":""}],
    types: placeholder as Registry['panel.legacy.kelas']['types'],
  },
  'panel.legacy.siswa': {
    methods: ["GET","HEAD"],
    pattern: '/panel/siswa',
    tokens: [{"old":"/panel/siswa","type":0,"val":"panel","end":""},{"old":"/panel/siswa","type":0,"val":"siswa","end":""}],
    types: placeholder as Registry['panel.legacy.siswa']['types'],
  },
  'panel.legacy.asesmen-paud': {
    methods: ["GET","HEAD"],
    pattern: '/panel/asesmen-paud',
    tokens: [{"old":"/panel/asesmen-paud","type":0,"val":"panel","end":""},{"old":"/panel/asesmen-paud","type":0,"val":"asesmen-paud","end":""}],
    types: placeholder as Registry['panel.legacy.asesmen-paud']['types'],
  },
  'panel.legacy.rapor': {
    methods: ["GET","HEAD"],
    pattern: '/panel/rapor',
    tokens: [{"old":"/panel/rapor","type":0,"val":"panel","end":""},{"old":"/panel/rapor","type":0,"val":"rapor","end":""}],
    types: placeholder as Registry['panel.legacy.rapor']['types'],
  },
  'glossary.index': {
    methods: ["GET","HEAD"],
    pattern: '/glossary',
    tokens: [{"old":"/glossary","type":0,"val":"glossary","end":""}],
    types: placeholder as Registry['glossary.index']['types'],
  },
  'curriculum.index': {
    methods: ["GET","HEAD"],
    pattern: '/curriculum',
    tokens: [{"old":"/curriculum","type":0,"val":"curriculum","end":""}],
    types: placeholder as Registry['curriculum.index']['types'],
  },
  'curriculum.print': {
    methods: ["GET","HEAD"],
    pattern: '/curriculum/print',
    tokens: [{"old":"/curriculum/print","type":0,"val":"curriculum","end":""},{"old":"/curriculum/print","type":0,"val":"print","end":""}],
    types: placeholder as Registry['curriculum.print']['types'],
  },
  'curriculum.export': {
    methods: ["GET","HEAD"],
    pattern: '/curriculum/export',
    tokens: [{"old":"/curriculum/export","type":0,"val":"curriculum","end":""},{"old":"/curriculum/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['curriculum.export']['types'],
  },
  'curriculum.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/curriculum/export/pdf',
    tokens: [{"old":"/curriculum/export/pdf","type":0,"val":"curriculum","end":""},{"old":"/curriculum/export/pdf","type":0,"val":"export","end":""},{"old":"/curriculum/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['curriculum.exportPdf']['types'],
  },
  'documents.autosave': {
    methods: ["POST"],
    pattern: '/documents/:type/:id/autosave',
    tokens: [{"old":"/documents/:type/:id/autosave","type":0,"val":"documents","end":""},{"old":"/documents/:type/:id/autosave","type":1,"val":"type","end":""},{"old":"/documents/:type/:id/autosave","type":1,"val":"id","end":""},{"old":"/documents/:type/:id/autosave","type":0,"val":"autosave","end":""}],
    types: placeholder as Registry['documents.autosave']['types'],
  },
  'documents.status': {
    methods: ["POST"],
    pattern: '/documents/:type/:id/status',
    tokens: [{"old":"/documents/:type/:id/status","type":0,"val":"documents","end":""},{"old":"/documents/:type/:id/status","type":1,"val":"type","end":""},{"old":"/documents/:type/:id/status","type":1,"val":"id","end":""},{"old":"/documents/:type/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['documents.status']['types'],
  },
  'documents.duplicate': {
    methods: ["POST"],
    pattern: '/documents/:type/:id/duplicate',
    tokens: [{"old":"/documents/:type/:id/duplicate","type":0,"val":"documents","end":""},{"old":"/documents/:type/:id/duplicate","type":1,"val":"type","end":""},{"old":"/documents/:type/:id/duplicate","type":1,"val":"id","end":""},{"old":"/documents/:type/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['documents.duplicate']['types'],
  },
  'curriculum.objectives.store': {
    methods: ["POST"],
    pattern: '/curriculum/objectives',
    tokens: [{"old":"/curriculum/objectives","type":0,"val":"curriculum","end":""},{"old":"/curriculum/objectives","type":0,"val":"objectives","end":""}],
    types: placeholder as Registry['curriculum.objectives.store']['types'],
  },
  'curriculum.objectives.destroy': {
    methods: ["DELETE"],
    pattern: '/curriculum/objectives/:id',
    tokens: [{"old":"/curriculum/objectives/:id","type":0,"val":"curriculum","end":""},{"old":"/curriculum/objectives/:id","type":0,"val":"objectives","end":""},{"old":"/curriculum/objectives/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['curriculum.objectives.destroy']['types'],
  },
  'curriculum.sequences.store': {
    methods: ["POST"],
    pattern: '/curriculum/sequences',
    tokens: [{"old":"/curriculum/sequences","type":0,"val":"curriculum","end":""},{"old":"/curriculum/sequences","type":0,"val":"sequences","end":""}],
    types: placeholder as Registry['curriculum.sequences.store']['types'],
  },
  'curriculum.sequences.update': {
    methods: ["PUT"],
    pattern: '/curriculum/sequences/:id',
    tokens: [{"old":"/curriculum/sequences/:id","type":0,"val":"curriculum","end":""},{"old":"/curriculum/sequences/:id","type":0,"val":"sequences","end":""},{"old":"/curriculum/sequences/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['curriculum.sequences.update']['types'],
  },
  'curriculum.sequences.destroy': {
    methods: ["DELETE"],
    pattern: '/curriculum/sequences/:id',
    tokens: [{"old":"/curriculum/sequences/:id","type":0,"val":"curriculum","end":""},{"old":"/curriculum/sequences/:id","type":0,"val":"sequences","end":""},{"old":"/curriculum/sequences/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['curriculum.sequences.destroy']['types'],
  },
  'curriculum.indicators.store': {
    methods: ["POST"],
    pattern: '/curriculum/indicators',
    tokens: [{"old":"/curriculum/indicators","type":0,"val":"curriculum","end":""},{"old":"/curriculum/indicators","type":0,"val":"indicators","end":""}],
    types: placeholder as Registry['curriculum.indicators.store']['types'],
  },
  'curriculum.presets.seed': {
    methods: ["POST"],
    pattern: '/curriculum/seed-presets',
    tokens: [{"old":"/curriculum/seed-presets","type":0,"val":"curriculum","end":""},{"old":"/curriculum/seed-presets","type":0,"val":"seed-presets","end":""}],
    types: placeholder as Registry['curriculum.presets.seed']['types'],
  },
  'curriculum.presets.reset': {
    methods: ["POST"],
    pattern: '/curriculum/reset-presets',
    tokens: [{"old":"/curriculum/reset-presets","type":0,"val":"curriculum","end":""},{"old":"/curriculum/reset-presets","type":0,"val":"reset-presets","end":""}],
    types: placeholder as Registry['curriculum.presets.reset']['types'],
  },
  'classes.index': {
    methods: ["GET","HEAD"],
    pattern: '/classes',
    tokens: [{"old":"/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['classes.index']['types'],
  },
  'classes.store': {
    methods: ["POST"],
    pattern: '/classes',
    tokens: [{"old":"/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['classes.store']['types'],
  },
  'classes.show': {
    methods: ["GET","HEAD"],
    pattern: '/classes/:id',
    tokens: [{"old":"/classes/:id","type":0,"val":"classes","end":""},{"old":"/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['classes.show']['types'],
  },
  'classes.update': {
    methods: ["PUT"],
    pattern: '/classes/:id',
    tokens: [{"old":"/classes/:id","type":0,"val":"classes","end":""},{"old":"/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['classes.update']['types'],
  },
  'classes.destroy': {
    methods: ["DELETE"],
    pattern: '/classes/:id',
    tokens: [{"old":"/classes/:id","type":0,"val":"classes","end":""},{"old":"/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['classes.destroy']['types'],
  },
  'classes.addStudent': {
    methods: ["POST"],
    pattern: '/classes/:id/students',
    tokens: [{"old":"/classes/:id/students","type":0,"val":"classes","end":""},{"old":"/classes/:id/students","type":1,"val":"id","end":""},{"old":"/classes/:id/students","type":0,"val":"students","end":""}],
    types: placeholder as Registry['classes.addStudent']['types'],
  },
  'classes.importStudents': {
    methods: ["POST"],
    pattern: '/classes/:id/students/import',
    tokens: [{"old":"/classes/:id/students/import","type":0,"val":"classes","end":""},{"old":"/classes/:id/students/import","type":1,"val":"id","end":""},{"old":"/classes/:id/students/import","type":0,"val":"students","end":""},{"old":"/classes/:id/students/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['classes.importStudents']['types'],
  },
  'classes.updateStudent': {
    methods: ["PUT"],
    pattern: '/classes/:id/students/:studentId',
    tokens: [{"old":"/classes/:id/students/:studentId","type":0,"val":"classes","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"id","end":""},{"old":"/classes/:id/students/:studentId","type":0,"val":"students","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"studentId","end":""}],
    types: placeholder as Registry['classes.updateStudent']['types'],
  },
  'classes.removeStudent': {
    methods: ["DELETE"],
    pattern: '/classes/:id/students/:studentId',
    tokens: [{"old":"/classes/:id/students/:studentId","type":0,"val":"classes","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"id","end":""},{"old":"/classes/:id/students/:studentId","type":0,"val":"students","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"studentId","end":""}],
    types: placeholder as Registry['classes.removeStudent']['types'],
  },
  'teaching-modules.index': {
    methods: ["GET","HEAD"],
    pattern: '/teaching-modules',
    tokens: [{"old":"/teaching-modules","type":0,"val":"teaching-modules","end":""}],
    types: placeholder as Registry['teaching-modules.index']['types'],
  },
  'teaching-modules.store': {
    methods: ["POST"],
    pattern: '/teaching-modules',
    tokens: [{"old":"/teaching-modules","type":0,"val":"teaching-modules","end":""}],
    types: placeholder as Registry['teaching-modules.store']['types'],
  },
  'teaching-modules.show': {
    methods: ["GET","HEAD"],
    pattern: '/teaching-modules/:id',
    tokens: [{"old":"/teaching-modules/:id","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['teaching-modules.show']['types'],
  },
  'teaching-modules.update': {
    methods: ["PUT"],
    pattern: '/teaching-modules/:id',
    tokens: [{"old":"/teaching-modules/:id","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['teaching-modules.update']['types'],
  },
  'teaching-modules.destroy': {
    methods: ["DELETE"],
    pattern: '/teaching-modules/:id',
    tokens: [{"old":"/teaching-modules/:id","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['teaching-modules.destroy']['types'],
  },
  'teaching-modules.generate': {
    methods: ["POST"],
    pattern: '/teaching-modules/generate',
    tokens: [{"old":"/teaching-modules/generate","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['teaching-modules.generate']['types'],
  },
  'teaching-modules.export': {
    methods: ["GET","HEAD"],
    pattern: '/teaching-modules/:id/export',
    tokens: [{"old":"/teaching-modules/:id/export","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id/export","type":1,"val":"id","end":""},{"old":"/teaching-modules/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['teaching-modules.export']['types'],
  },
  'teaching-modules.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/teaching-modules/:id/export/pdf',
    tokens: [{"old":"/teaching-modules/:id/export/pdf","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/teaching-modules/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/teaching-modules/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['teaching-modules.exportPdf']['types'],
  },
  'exams.index': {
    methods: ["GET","HEAD"],
    pattern: '/exams',
    tokens: [{"old":"/exams","type":0,"val":"exams","end":""}],
    types: placeholder as Registry['exams.index']['types'],
  },
  'exams.store': {
    methods: ["POST"],
    pattern: '/exams',
    tokens: [{"old":"/exams","type":0,"val":"exams","end":""}],
    types: placeholder as Registry['exams.store']['types'],
  },
  'exams.generationStatus': {
    methods: ["GET","HEAD"],
    pattern: '/exams/:id/generation-status',
    tokens: [{"old":"/exams/:id/generation-status","type":0,"val":"exams","end":""},{"old":"/exams/:id/generation-status","type":1,"val":"id","end":""},{"old":"/exams/:id/generation-status","type":0,"val":"generation-status","end":""}],
    types: placeholder as Registry['exams.generationStatus']['types'],
  },
  'exams.show': {
    methods: ["GET","HEAD"],
    pattern: '/exams/:id',
    tokens: [{"old":"/exams/:id","type":0,"val":"exams","end":""},{"old":"/exams/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['exams.show']['types'],
  },
  'exams.uploadImage': {
    methods: ["POST"],
    pattern: '/exams/:id/upload-image',
    tokens: [{"old":"/exams/:id/upload-image","type":0,"val":"exams","end":""},{"old":"/exams/:id/upload-image","type":1,"val":"id","end":""},{"old":"/exams/:id/upload-image","type":0,"val":"upload-image","end":""}],
    types: placeholder as Registry['exams.uploadImage']['types'],
  },
  'exams.update': {
    methods: ["PUT"],
    pattern: '/exams/:id',
    tokens: [{"old":"/exams/:id","type":0,"val":"exams","end":""},{"old":"/exams/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['exams.update']['types'],
  },
  'exams.destroy': {
    methods: ["DELETE"],
    pattern: '/exams/:id',
    tokens: [{"old":"/exams/:id","type":0,"val":"exams","end":""},{"old":"/exams/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['exams.destroy']['types'],
  },
  'exams.generate': {
    methods: ["POST"],
    pattern: '/exams/generate',
    tokens: [{"old":"/exams/generate","type":0,"val":"exams","end":""},{"old":"/exams/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['exams.generate']['types'],
  },
  'exams.export': {
    methods: ["GET","HEAD"],
    pattern: '/exams/:id/export',
    tokens: [{"old":"/exams/:id/export","type":0,"val":"exams","end":""},{"old":"/exams/:id/export","type":1,"val":"id","end":""},{"old":"/exams/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['exams.export']['types'],
  },
  'exams.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/exams/:id/export/pdf',
    tokens: [{"old":"/exams/:id/export/pdf","type":0,"val":"exams","end":""},{"old":"/exams/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/exams/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/exams/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['exams.exportPdf']['types'],
  },
  'exams.printPreview': {
    methods: ["GET","HEAD"],
    pattern: '/exams/:id/print-preview',
    tokens: [{"old":"/exams/:id/print-preview","type":0,"val":"exams","end":""},{"old":"/exams/:id/print-preview","type":1,"val":"id","end":""},{"old":"/exams/:id/print-preview","type":0,"val":"print-preview","end":""}],
    types: placeholder as Registry['exams.printPreview']['types'],
  },
  'annual-plans.index': {
    methods: ["GET","HEAD"],
    pattern: '/annual-plans',
    tokens: [{"old":"/annual-plans","type":0,"val":"annual-plans","end":""}],
    types: placeholder as Registry['annual-plans.index']['types'],
  },
  'annual-plans.store': {
    methods: ["POST"],
    pattern: '/annual-plans',
    tokens: [{"old":"/annual-plans","type":0,"val":"annual-plans","end":""}],
    types: placeholder as Registry['annual-plans.store']['types'],
  },
  'annual-plans.show': {
    methods: ["GET","HEAD"],
    pattern: '/annual-plans/:id',
    tokens: [{"old":"/annual-plans/:id","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annual-plans.show']['types'],
  },
  'annual-plans.update': {
    methods: ["PUT"],
    pattern: '/annual-plans/:id',
    tokens: [{"old":"/annual-plans/:id","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annual-plans.update']['types'],
  },
  'annual-plans.destroy': {
    methods: ["DELETE"],
    pattern: '/annual-plans/:id',
    tokens: [{"old":"/annual-plans/:id","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annual-plans.destroy']['types'],
  },
  'annual-plans.generate': {
    methods: ["POST"],
    pattern: '/annual-plans/generate',
    tokens: [{"old":"/annual-plans/generate","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['annual-plans.generate']['types'],
  },
  'annual-plans.export': {
    methods: ["GET","HEAD"],
    pattern: '/annual-plans/:id/export',
    tokens: [{"old":"/annual-plans/:id/export","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id/export","type":1,"val":"id","end":""},{"old":"/annual-plans/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['annual-plans.export']['types'],
  },
  'annual-plans.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/annual-plans/:id/export/pdf',
    tokens: [{"old":"/annual-plans/:id/export/pdf","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/annual-plans/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/annual-plans/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['annual-plans.exportPdf']['types'],
  },
  'semester-plans.index': {
    methods: ["GET","HEAD"],
    pattern: '/semester-plans',
    tokens: [{"old":"/semester-plans","type":0,"val":"semester-plans","end":""}],
    types: placeholder as Registry['semester-plans.index']['types'],
  },
  'semester-plans.store': {
    methods: ["POST"],
    pattern: '/semester-plans',
    tokens: [{"old":"/semester-plans","type":0,"val":"semester-plans","end":""}],
    types: placeholder as Registry['semester-plans.store']['types'],
  },
  'semester-plans.show': {
    methods: ["GET","HEAD"],
    pattern: '/semester-plans/:id',
    tokens: [{"old":"/semester-plans/:id","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['semester-plans.show']['types'],
  },
  'semester-plans.update': {
    methods: ["PUT"],
    pattern: '/semester-plans/:id',
    tokens: [{"old":"/semester-plans/:id","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['semester-plans.update']['types'],
  },
  'semester-plans.destroy': {
    methods: ["DELETE"],
    pattern: '/semester-plans/:id',
    tokens: [{"old":"/semester-plans/:id","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['semester-plans.destroy']['types'],
  },
  'semester-plans.generate': {
    methods: ["POST"],
    pattern: '/semester-plans/generate',
    tokens: [{"old":"/semester-plans/generate","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['semester-plans.generate']['types'],
  },
  'semester-plans.export': {
    methods: ["GET","HEAD"],
    pattern: '/semester-plans/:id/export',
    tokens: [{"old":"/semester-plans/:id/export","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id/export","type":1,"val":"id","end":""},{"old":"/semester-plans/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['semester-plans.export']['types'],
  },
  'semester-plans.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/semester-plans/:id/export/pdf',
    tokens: [{"old":"/semester-plans/:id/export/pdf","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/semester-plans/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/semester-plans/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['semester-plans.exportPdf']['types'],
  },
  'rppm.index': {
    methods: ["GET","HEAD"],
    pattern: '/rppm',
    tokens: [{"old":"/rppm","type":0,"val":"rppm","end":""}],
    types: placeholder as Registry['rppm.index']['types'],
  },
  'rppm.show': {
    methods: ["GET","HEAD"],
    pattern: '/rppm/:id',
    tokens: [{"old":"/rppm/:id","type":0,"val":"rppm","end":""},{"old":"/rppm/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rppm.show']['types'],
  },
  'rppm.export': {
    methods: ["GET","HEAD"],
    pattern: '/rppm/:id/export',
    tokens: [{"old":"/rppm/:id/export","type":0,"val":"rppm","end":""},{"old":"/rppm/:id/export","type":1,"val":"id","end":""},{"old":"/rppm/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['rppm.export']['types'],
  },
  'rppm.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/rppm/:id/export/pdf',
    tokens: [{"old":"/rppm/:id/export/pdf","type":0,"val":"rppm","end":""},{"old":"/rppm/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/rppm/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/rppm/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['rppm.exportPdf']['types'],
  },
  'rppm.update': {
    methods: ["PUT"],
    pattern: '/rppm/:id',
    tokens: [{"old":"/rppm/:id","type":0,"val":"rppm","end":""},{"old":"/rppm/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rppm.update']['types'],
  },
  'rppm.destroy': {
    methods: ["DELETE"],
    pattern: '/rppm/:id',
    tokens: [{"old":"/rppm/:id","type":0,"val":"rppm","end":""},{"old":"/rppm/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rppm.destroy']['types'],
  },
  'rppm.generate': {
    methods: ["POST"],
    pattern: '/rppm/generate',
    tokens: [{"old":"/rppm/generate","type":0,"val":"rppm","end":""},{"old":"/rppm/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['rppm.generate']['types'],
  },
  'rpph.index': {
    methods: ["GET","HEAD"],
    pattern: '/rpph',
    tokens: [{"old":"/rpph","type":0,"val":"rpph","end":""}],
    types: placeholder as Registry['rpph.index']['types'],
  },
  'rpph.show': {
    methods: ["GET","HEAD"],
    pattern: '/rpph/:id',
    tokens: [{"old":"/rpph/:id","type":0,"val":"rpph","end":""},{"old":"/rpph/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rpph.show']['types'],
  },
  'rpph.export': {
    methods: ["GET","HEAD"],
    pattern: '/rpph/:id/export',
    tokens: [{"old":"/rpph/:id/export","type":0,"val":"rpph","end":""},{"old":"/rpph/:id/export","type":1,"val":"id","end":""},{"old":"/rpph/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['rpph.export']['types'],
  },
  'rpph.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/rpph/:id/export/pdf',
    tokens: [{"old":"/rpph/:id/export/pdf","type":0,"val":"rpph","end":""},{"old":"/rpph/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/rpph/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/rpph/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['rpph.exportPdf']['types'],
  },
  'rpph.update': {
    methods: ["PUT"],
    pattern: '/rpph/:id',
    tokens: [{"old":"/rpph/:id","type":0,"val":"rpph","end":""},{"old":"/rpph/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rpph.update']['types'],
  },
  'rpph.destroy': {
    methods: ["DELETE"],
    pattern: '/rpph/:id',
    tokens: [{"old":"/rpph/:id","type":0,"val":"rpph","end":""},{"old":"/rpph/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rpph.destroy']['types'],
  },
  'rpph.generate': {
    methods: ["POST"],
    pattern: '/rpph/generate',
    tokens: [{"old":"/rpph/generate","type":0,"val":"rpph","end":""},{"old":"/rpph/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['rpph.generate']['types'],
  },
  'lkpd.show': {
    methods: ["GET","HEAD"],
    pattern: '/lkpd/:id',
    tokens: [{"old":"/lkpd/:id","type":0,"val":"lkpd","end":""},{"old":"/lkpd/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['lkpd.show']['types'],
  },
  'lkpd.export': {
    methods: ["GET","HEAD"],
    pattern: '/lkpd/:id/export',
    tokens: [{"old":"/lkpd/:id/export","type":0,"val":"lkpd","end":""},{"old":"/lkpd/:id/export","type":1,"val":"id","end":""},{"old":"/lkpd/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['lkpd.export']['types'],
  },
  'lkpd.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/lkpd/:id/export/pdf',
    tokens: [{"old":"/lkpd/:id/export/pdf","type":0,"val":"lkpd","end":""},{"old":"/lkpd/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/lkpd/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/lkpd/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['lkpd.exportPdf']['types'],
  },
  'lkpd.destroy': {
    methods: ["DELETE"],
    pattern: '/lkpd/:id',
    tokens: [{"old":"/lkpd/:id","type":0,"val":"lkpd","end":""},{"old":"/lkpd/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['lkpd.destroy']['types'],
  },
  'lkpd.generate': {
    methods: ["POST"],
    pattern: '/lkpd/generate',
    tokens: [{"old":"/lkpd/generate","type":0,"val":"lkpd","end":""},{"old":"/lkpd/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['lkpd.generate']['types'],
  },
  'media-modules.index': {
    methods: ["GET","HEAD"],
    pattern: '/media-modules',
    tokens: [{"old":"/media-modules","type":0,"val":"media-modules","end":""}],
    types: placeholder as Registry['media-modules.index']['types'],
  },
  'media-modules.show': {
    methods: ["GET","HEAD"],
    pattern: '/media-modules/:id',
    tokens: [{"old":"/media-modules/:id","type":0,"val":"media-modules","end":""},{"old":"/media-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media-modules.show']['types'],
  },
  'media-modules.destroy': {
    methods: ["DELETE"],
    pattern: '/media-modules/:id',
    tokens: [{"old":"/media-modules/:id","type":0,"val":"media-modules","end":""},{"old":"/media-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['media-modules.destroy']['types'],
  },
  'media-modules.generate': {
    methods: ["POST"],
    pattern: '/media-modules/generate',
    tokens: [{"old":"/media-modules/generate","type":0,"val":"media-modules","end":""},{"old":"/media-modules/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['media-modules.generate']['types'],
  },
  'media-modules.exportPptx': {
    methods: ["GET","HEAD"],
    pattern: '/media-modules/:id/export/pptx',
    tokens: [{"old":"/media-modules/:id/export/pptx","type":0,"val":"media-modules","end":""},{"old":"/media-modules/:id/export/pptx","type":1,"val":"id","end":""},{"old":"/media-modules/:id/export/pptx","type":0,"val":"export","end":""},{"old":"/media-modules/:id/export/pptx","type":0,"val":"pptx","end":""}],
    types: placeholder as Registry['media-modules.exportPptx']['types'],
  },
  'media-modules.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/media-modules/:id/export/pdf',
    tokens: [{"old":"/media-modules/:id/export/pdf","type":0,"val":"media-modules","end":""},{"old":"/media-modules/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/media-modules/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/media-modules/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['media-modules.exportPdf']['types'],
  },
  'paud-assessments.index': {
    methods: ["GET","HEAD"],
    pattern: '/paud-assessments',
    tokens: [{"old":"/paud-assessments","type":0,"val":"paud-assessments","end":""}],
    types: placeholder as Registry['paud-assessments.index']['types'],
  },
  'paud-assessments.store': {
    methods: ["POST"],
    pattern: '/paud-assessments',
    tokens: [{"old":"/paud-assessments","type":0,"val":"paud-assessments","end":""}],
    types: placeholder as Registry['paud-assessments.store']['types'],
  },
  'paud-assessments.generateAi': {
    methods: ["POST"],
    pattern: '/paud-assessments/generate-ai',
    tokens: [{"old":"/paud-assessments/generate-ai","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/generate-ai","type":0,"val":"generate-ai","end":""}],
    types: placeholder as Registry['paud-assessments.generateAi']['types'],
  },
  'paud-assessments.exportBundle': {
    methods: ["GET","HEAD"],
    pattern: '/paud-assessments/export-bundle',
    tokens: [{"old":"/paud-assessments/export-bundle","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/export-bundle","type":0,"val":"export-bundle","end":""}],
    types: placeholder as Registry['paud-assessments.exportBundle']['types'],
  },
  'paud-assessments.exportBundlePdf': {
    methods: ["GET","HEAD"],
    pattern: '/paud-assessments/export-bundle/pdf',
    tokens: [{"old":"/paud-assessments/export-bundle/pdf","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/export-bundle/pdf","type":0,"val":"export-bundle","end":""},{"old":"/paud-assessments/export-bundle/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['paud-assessments.exportBundlePdf']['types'],
  },
  'paud-assessments.update': {
    methods: ["PUT"],
    pattern: '/paud-assessments/:id',
    tokens: [{"old":"/paud-assessments/:id","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['paud-assessments.update']['types'],
  },
  'paud-assessments.destroy': {
    methods: ["DELETE"],
    pattern: '/paud-assessments/:id',
    tokens: [{"old":"/paud-assessments/:id","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['paud-assessments.destroy']['types'],
  },
  'paud-assessments.export': {
    methods: ["GET","HEAD"],
    pattern: '/paud-assessments/:id/export',
    tokens: [{"old":"/paud-assessments/:id/export","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/:id/export","type":1,"val":"id","end":""},{"old":"/paud-assessments/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['paud-assessments.export']['types'],
  },
  'paud-assessments.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/paud-assessments/:id/export/pdf',
    tokens: [{"old":"/paud-assessments/:id/export/pdf","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/paud-assessments/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/paud-assessments/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['paud-assessments.exportPdf']['types'],
  },
  'paud-assessments.attachments.show': {
    methods: ["GET","HEAD"],
    pattern: '/paud-assessments/:id/attachments/:attachmentId',
    tokens: [{"old":"/paud-assessments/:id/attachments/:attachmentId","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/:id/attachments/:attachmentId","type":1,"val":"id","end":""},{"old":"/paud-assessments/:id/attachments/:attachmentId","type":0,"val":"attachments","end":""},{"old":"/paud-assessments/:id/attachments/:attachmentId","type":1,"val":"attachmentId","end":""}],
    types: placeholder as Registry['paud-assessments.attachments.show']['types'],
  },
  'assessments.index': {
    methods: ["GET","HEAD"],
    pattern: '/assessments',
    tokens: [{"old":"/assessments","type":0,"val":"assessments","end":""}],
    types: placeholder as Registry['assessments.index']['types'],
  },
  'assessments.store': {
    methods: ["POST"],
    pattern: '/assessments',
    tokens: [{"old":"/assessments","type":0,"val":"assessments","end":""}],
    types: placeholder as Registry['assessments.store']['types'],
  },
  'assessments.show': {
    methods: ["GET","HEAD"],
    pattern: '/assessments/:id',
    tokens: [{"old":"/assessments/:id","type":0,"val":"assessments","end":""},{"old":"/assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['assessments.show']['types'],
  },
  'assessments.updateScores': {
    methods: ["PUT"],
    pattern: '/assessments/:id/scores',
    tokens: [{"old":"/assessments/:id/scores","type":0,"val":"assessments","end":""},{"old":"/assessments/:id/scores","type":1,"val":"id","end":""},{"old":"/assessments/:id/scores","type":0,"val":"scores","end":""}],
    types: placeholder as Registry['assessments.updateScores']['types'],
  },
  'assessments.destroy': {
    methods: ["DELETE"],
    pattern: '/assessments/:id',
    tokens: [{"old":"/assessments/:id","type":0,"val":"assessments","end":""},{"old":"/assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['assessments.destroy']['types'],
  },
  'assessments.export': {
    methods: ["GET","HEAD"],
    pattern: '/assessments/:id/export',
    tokens: [{"old":"/assessments/:id/export","type":0,"val":"assessments","end":""},{"old":"/assessments/:id/export","type":1,"val":"id","end":""},{"old":"/assessments/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['assessments.export']['types'],
  },
  'assessments.exportDocx': {
    methods: ["GET","HEAD"],
    pattern: '/assessments/:id/export/docx',
    tokens: [{"old":"/assessments/:id/export/docx","type":0,"val":"assessments","end":""},{"old":"/assessments/:id/export/docx","type":1,"val":"id","end":""},{"old":"/assessments/:id/export/docx","type":0,"val":"export","end":""},{"old":"/assessments/:id/export/docx","type":0,"val":"docx","end":""}],
    types: placeholder as Registry['assessments.exportDocx']['types'],
  },
  'assessments.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/assessments/:id/export/pdf',
    tokens: [{"old":"/assessments/:id/export/pdf","type":0,"val":"assessments","end":""},{"old":"/assessments/:id/export/pdf","type":1,"val":"id","end":""},{"old":"/assessments/:id/export/pdf","type":0,"val":"export","end":""},{"old":"/assessments/:id/export/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['assessments.exportPdf']['types'],
  },
  'principal.index': {
    methods: ["GET","HEAD"],
    pattern: '/principal',
    tokens: [{"old":"/principal","type":0,"val":"principal","end":""}],
    types: placeholder as Registry['principal.index']['types'],
  },
  'principal.teacher': {
    methods: ["GET","HEAD"],
    pattern: '/principal/teachers/:userId',
    tokens: [{"old":"/principal/teachers/:userId","type":0,"val":"principal","end":""},{"old":"/principal/teachers/:userId","type":0,"val":"teachers","end":""},{"old":"/principal/teachers/:userId","type":1,"val":"userId","end":""}],
    types: placeholder as Registry['principal.teacher']['types'],
  },
  'report-cards.index': {
    methods: ["GET","HEAD"],
    pattern: '/report-cards',
    tokens: [{"old":"/report-cards","type":0,"val":"report-cards","end":""}],
    types: placeholder as Registry['report-cards.index']['types'],
  },
  'report-cards.show': {
    methods: ["GET","HEAD"],
    pattern: '/report-cards/:classId/:semesterId',
    tokens: [{"old":"/report-cards/:classId/:semesterId","type":0,"val":"report-cards","end":""},{"old":"/report-cards/:classId/:semesterId","type":1,"val":"classId","end":""},{"old":"/report-cards/:classId/:semesterId","type":1,"val":"semesterId","end":""}],
    types: placeholder as Registry['report-cards.show']['types'],
  },
  'report-cards.exportPdf': {
    methods: ["GET","HEAD"],
    pattern: '/report-cards/:classId/:semesterId/:studentId/export',
    tokens: [{"old":"/report-cards/:classId/:semesterId/:studentId/export","type":0,"val":"report-cards","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export","type":1,"val":"classId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export","type":1,"val":"semesterId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export","type":1,"val":"studentId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['report-cards.exportPdf']['types'],
  },
  'report-cards.exportDocx': {
    methods: ["GET","HEAD"],
    pattern: '/report-cards/:classId/:semesterId/:studentId/export/docx',
    tokens: [{"old":"/report-cards/:classId/:semesterId/:studentId/export/docx","type":0,"val":"report-cards","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export/docx","type":1,"val":"classId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export/docx","type":1,"val":"semesterId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export/docx","type":1,"val":"studentId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export/docx","type":0,"val":"export","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/export/docx","type":0,"val":"docx","end":""}],
    types: placeholder as Registry['report-cards.exportDocx']['types'],
  },
  'report-cards.narratives.save': {
    methods: ["POST"],
    pattern: '/report-cards/:classId/:semesterId/:studentId/narratives',
    tokens: [{"old":"/report-cards/:classId/:semesterId/:studentId/narratives","type":0,"val":"report-cards","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/narratives","type":1,"val":"classId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/narratives","type":1,"val":"semesterId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/narratives","type":1,"val":"studentId","end":""},{"old":"/report-cards/:classId/:semesterId/:studentId/narratives","type":0,"val":"narratives","end":""}],
    types: placeholder as Registry['report-cards.narratives.save']['types'],
  },
  'report-cards.narratives.generate': {
    methods: ["POST"],
    pattern: '/report-cards/:classId/:semesterId/narratives/generate',
    tokens: [{"old":"/report-cards/:classId/:semesterId/narratives/generate","type":0,"val":"report-cards","end":""},{"old":"/report-cards/:classId/:semesterId/narratives/generate","type":1,"val":"classId","end":""},{"old":"/report-cards/:classId/:semesterId/narratives/generate","type":1,"val":"semesterId","end":""},{"old":"/report-cards/:classId/:semesterId/narratives/generate","type":0,"val":"narratives","end":""},{"old":"/report-cards/:classId/:semesterId/narratives/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['report-cards.narratives.generate']['types'],
  },
  'report-narratives.approve': {
    methods: ["POST"],
    pattern: '/report-narratives/:id/approve',
    tokens: [{"old":"/report-narratives/:id/approve","type":0,"val":"report-narratives","end":""},{"old":"/report-narratives/:id/approve","type":1,"val":"id","end":""},{"old":"/report-narratives/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['report-narratives.approve']['types'],
  },
  'subjects.index': {
    methods: ["GET","HEAD"],
    pattern: '/subjects',
    tokens: [{"old":"/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['subjects.index']['types'],
  },
  'subjects.store': {
    methods: ["POST"],
    pattern: '/subjects',
    tokens: [{"old":"/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['subjects.store']['types'],
  },
  'subjects.storeDefaults': {
    methods: ["POST"],
    pattern: '/subjects/defaults',
    tokens: [{"old":"/subjects/defaults","type":0,"val":"subjects","end":""},{"old":"/subjects/defaults","type":0,"val":"defaults","end":""}],
    types: placeholder as Registry['subjects.storeDefaults']['types'],
  },
  'subjects.update': {
    methods: ["PUT"],
    pattern: '/subjects/:id',
    tokens: [{"old":"/subjects/:id","type":0,"val":"subjects","end":""},{"old":"/subjects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['subjects.update']['types'],
  },
  'subjects.destroy': {
    methods: ["DELETE"],
    pattern: '/subjects/:id',
    tokens: [{"old":"/subjects/:id","type":0,"val":"subjects","end":""},{"old":"/subjects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['subjects.destroy']['types'],
  },
  'settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.index']['types'],
  },
  'settings.update': {
    methods: ["PUT"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.update']['types'],
  },
  'admin.users.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.index']['types'],
  },
  'admin.users.update': {
    methods: ["PUT"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.update']['types'],
  },
  'admin.users.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.destroy']['types'],
  },
  'admin.fraud.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/fraud-cases',
    tokens: [{"old":"/admin/fraud-cases","type":0,"val":"admin","end":""},{"old":"/admin/fraud-cases","type":0,"val":"fraud-cases","end":""}],
    types: placeholder as Registry['admin.fraud.index']['types'],
  },
  'admin.fraud.review': {
    methods: ["PUT"],
    pattern: '/admin/fraud-cases/:id',
    tokens: [{"old":"/admin/fraud-cases/:id","type":0,"val":"admin","end":""},{"old":"/admin/fraud-cases/:id","type":0,"val":"fraud-cases","end":""},{"old":"/admin/fraud-cases/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.fraud.review']['types'],
  },
  'admin.packages.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/packages',
    tokens: [{"old":"/admin/packages","type":0,"val":"admin","end":""},{"old":"/admin/packages","type":0,"val":"packages","end":""}],
    types: placeholder as Registry['admin.packages.index']['types'],
  },
  'admin.packages.store': {
    methods: ["POST"],
    pattern: '/admin/packages',
    tokens: [{"old":"/admin/packages","type":0,"val":"admin","end":""},{"old":"/admin/packages","type":0,"val":"packages","end":""}],
    types: placeholder as Registry['admin.packages.store']['types'],
  },
  'admin.packages.update': {
    methods: ["PUT"],
    pattern: '/admin/packages/:id',
    tokens: [{"old":"/admin/packages/:id","type":0,"val":"admin","end":""},{"old":"/admin/packages/:id","type":0,"val":"packages","end":""},{"old":"/admin/packages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.packages.update']['types'],
  },
  'admin.packages.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/packages/:id',
    tokens: [{"old":"/admin/packages/:id","type":0,"val":"admin","end":""},{"old":"/admin/packages/:id","type":0,"val":"packages","end":""},{"old":"/admin/packages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.packages.destroy']['types'],
  },
  'admin.entitlements.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/entitlements',
    tokens: [{"old":"/admin/entitlements","type":0,"val":"admin","end":""},{"old":"/admin/entitlements","type":0,"val":"entitlements","end":""}],
    types: placeholder as Registry['admin.entitlements.index']['types'],
  },
  'admin.entitlements.update': {
    methods: ["PUT"],
    pattern: '/admin/entitlements/:id',
    tokens: [{"old":"/admin/entitlements/:id","type":0,"val":"admin","end":""},{"old":"/admin/entitlements/:id","type":0,"val":"entitlements","end":""},{"old":"/admin/entitlements/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.entitlements.update']['types'],
  },
  'admin.academic-years.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/academic-years',
    tokens: [{"old":"/admin/academic-years","type":0,"val":"admin","end":""},{"old":"/admin/academic-years","type":0,"val":"academic-years","end":""}],
    types: placeholder as Registry['admin.academic-years.index']['types'],
  },
  'admin.academic-years.store': {
    methods: ["POST"],
    pattern: '/admin/academic-years',
    tokens: [{"old":"/admin/academic-years","type":0,"val":"admin","end":""},{"old":"/admin/academic-years","type":0,"val":"academic-years","end":""}],
    types: placeholder as Registry['admin.academic-years.store']['types'],
  },
  'admin.academic-years.update': {
    methods: ["PUT"],
    pattern: '/admin/academic-years/:id',
    tokens: [{"old":"/admin/academic-years/:id","type":0,"val":"admin","end":""},{"old":"/admin/academic-years/:id","type":0,"val":"academic-years","end":""},{"old":"/admin/academic-years/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.academic-years.update']['types'],
  },
  'admin.academic-years.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/academic-years/:id',
    tokens: [{"old":"/admin/academic-years/:id","type":0,"val":"admin","end":""},{"old":"/admin/academic-years/:id","type":0,"val":"academic-years","end":""},{"old":"/admin/academic-years/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.academic-years.destroy']['types'],
  },
  'admin.schools.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/schools',
    tokens: [{"old":"/admin/schools","type":0,"val":"admin","end":""},{"old":"/admin/schools","type":0,"val":"schools","end":""}],
    types: placeholder as Registry['admin.schools.index']['types'],
  },
  'admin.schools.store': {
    methods: ["POST"],
    pattern: '/admin/schools',
    tokens: [{"old":"/admin/schools","type":0,"val":"admin","end":""},{"old":"/admin/schools","type":0,"val":"schools","end":""}],
    types: placeholder as Registry['admin.schools.store']['types'],
  },
  'admin.schools.update': {
    methods: ["PUT"],
    pattern: '/admin/schools/:id',
    tokens: [{"old":"/admin/schools/:id","type":0,"val":"admin","end":""},{"old":"/admin/schools/:id","type":0,"val":"schools","end":""},{"old":"/admin/schools/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.schools.update']['types'],
  },
  'admin.schools.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/schools/:id',
    tokens: [{"old":"/admin/schools/:id","type":0,"val":"admin","end":""},{"old":"/admin/schools/:id","type":0,"val":"schools","end":""},{"old":"/admin/schools/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.schools.destroy']['types'],
  },
  'admin.ai-settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/ai-settings',
    tokens: [{"old":"/admin/ai-settings","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings","type":0,"val":"ai-settings","end":""}],
    types: placeholder as Registry['admin.ai-settings.index']['types'],
  },
  'admin.ai-settings.update': {
    methods: ["PUT"],
    pattern: '/admin/ai-settings',
    tokens: [{"old":"/admin/ai-settings","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings","type":0,"val":"ai-settings","end":""}],
    types: placeholder as Registry['admin.ai-settings.update']['types'],
  },
  'admin.ai-settings.test': {
    methods: ["POST"],
    pattern: '/admin/ai-settings/test',
    tokens: [{"old":"/admin/ai-settings/test","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings/test","type":0,"val":"ai-settings","end":""},{"old":"/admin/ai-settings/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['admin.ai-settings.test']['types'],
  },
  'admin.ai-settings.models': {
    methods: ["POST"],
    pattern: '/admin/ai-settings/models',
    tokens: [{"old":"/admin/ai-settings/models","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings/models","type":0,"val":"ai-settings","end":""},{"old":"/admin/ai-settings/models","type":0,"val":"models","end":""}],
    types: placeholder as Registry['admin.ai-settings.models']['types'],
  },
  'admin.ai-settings.oauth.openai.start': {
    methods: ["GET","HEAD"],
    pattern: '/admin/ai-settings/oauth/openai/start',
    tokens: [{"old":"/admin/ai-settings/oauth/openai/start","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings/oauth/openai/start","type":0,"val":"ai-settings","end":""},{"old":"/admin/ai-settings/oauth/openai/start","type":0,"val":"oauth","end":""},{"old":"/admin/ai-settings/oauth/openai/start","type":0,"val":"openai","end":""},{"old":"/admin/ai-settings/oauth/openai/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['admin.ai-settings.oauth.openai.start']['types'],
  },
  'admin.ai-settings.oauth.gemini.start': {
    methods: ["GET","HEAD"],
    pattern: '/admin/ai-settings/oauth/gemini/start',
    tokens: [{"old":"/admin/ai-settings/oauth/gemini/start","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings/oauth/gemini/start","type":0,"val":"ai-settings","end":""},{"old":"/admin/ai-settings/oauth/gemini/start","type":0,"val":"oauth","end":""},{"old":"/admin/ai-settings/oauth/gemini/start","type":0,"val":"gemini","end":""},{"old":"/admin/ai-settings/oauth/gemini/start","type":0,"val":"start","end":""}],
    types: placeholder as Registry['admin.ai-settings.oauth.gemini.start']['types'],
  },
  'admin.ai-settings.oauth.gemini.callback': {
    methods: ["GET","HEAD"],
    pattern: '/admin/ai-settings/oauth/gemini/callback',
    tokens: [{"old":"/admin/ai-settings/oauth/gemini/callback","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings/oauth/gemini/callback","type":0,"val":"ai-settings","end":""},{"old":"/admin/ai-settings/oauth/gemini/callback","type":0,"val":"oauth","end":""},{"old":"/admin/ai-settings/oauth/gemini/callback","type":0,"val":"gemini","end":""},{"old":"/admin/ai-settings/oauth/gemini/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['admin.ai-settings.oauth.gemini.callback']['types'],
  },
  'admin.curriculum-presets.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/curriculum-presets',
    tokens: [{"old":"/admin/curriculum-presets","type":0,"val":"admin","end":""},{"old":"/admin/curriculum-presets","type":0,"val":"curriculum-presets","end":""}],
    types: placeholder as Registry['admin.curriculum-presets.index']['types'],
  },
  'admin.curriculum-presets.store': {
    methods: ["POST"],
    pattern: '/admin/curriculum-presets',
    tokens: [{"old":"/admin/curriculum-presets","type":0,"val":"admin","end":""},{"old":"/admin/curriculum-presets","type":0,"val":"curriculum-presets","end":""}],
    types: placeholder as Registry['admin.curriculum-presets.store']['types'],
  },
  'admin.curriculum-presets.update': {
    methods: ["PUT"],
    pattern: '/admin/curriculum-presets/:id',
    tokens: [{"old":"/admin/curriculum-presets/:id","type":0,"val":"admin","end":""},{"old":"/admin/curriculum-presets/:id","type":0,"val":"curriculum-presets","end":""},{"old":"/admin/curriculum-presets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.curriculum-presets.update']['types'],
  },
  'admin.curriculum-presets.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/curriculum-presets/:id',
    tokens: [{"old":"/admin/curriculum-presets/:id","type":0,"val":"admin","end":""},{"old":"/admin/curriculum-presets/:id","type":0,"val":"curriculum-presets","end":""},{"old":"/admin/curriculum-presets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.curriculum-presets.destroy']['types'],
  },
  'admin.curriculum-presets.resetDefaults': {
    methods: ["POST"],
    pattern: '/admin/curriculum-presets/reset-defaults',
    tokens: [{"old":"/admin/curriculum-presets/reset-defaults","type":0,"val":"admin","end":""},{"old":"/admin/curriculum-presets/reset-defaults","type":0,"val":"curriculum-presets","end":""},{"old":"/admin/curriculum-presets/reset-defaults","type":0,"val":"reset-defaults","end":""}],
    types: placeholder as Registry['admin.curriculum-presets.resetDefaults']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
