/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['home']['types'],
  },
  'coming-soon': {
    methods: ["GET","HEAD"],
    pattern: '/coming-soon',
    tokens: [{"old":"/coming-soon","type":0,"val":"coming-soon","end":""}],
    types: placeholder as Registry['coming-soon']['types'],
  },
  'new_account.create': {
    methods: ["GET","HEAD"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.create']['types'],
  },
  'new_account.store': {
    methods: ["POST"],
    pattern: '/signup',
    tokens: [{"old":"/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['new_account.store']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'session.destroy': {
    methods: ["POST"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['session.destroy']['types'],
  },
  'onboarding.index': {
    methods: ["GET","HEAD"],
    pattern: '/onboarding',
    tokens: [{"old":"/onboarding","type":0,"val":"onboarding","end":""}],
    types: placeholder as Registry['onboarding.index']['types'],
  },
  'onboarding.store': {
    methods: ["POST"],
    pattern: '/onboarding',
    tokens: [{"old":"/onboarding","type":0,"val":"onboarding","end":""}],
    types: placeholder as Registry['onboarding.store']['types'],
  },
  'dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard']['types'],
  },
  'classes.index': {
    methods: ["GET","HEAD"],
    pattern: '/classes',
    tokens: [{"old":"/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['classes.index']['types'],
  },
  'classes.store': {
    methods: ["POST"],
    pattern: '/classes',
    tokens: [{"old":"/classes","type":0,"val":"classes","end":""}],
    types: placeholder as Registry['classes.store']['types'],
  },
  'classes.show': {
    methods: ["GET","HEAD"],
    pattern: '/classes/:id',
    tokens: [{"old":"/classes/:id","type":0,"val":"classes","end":""},{"old":"/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['classes.show']['types'],
  },
  'classes.update': {
    methods: ["PUT"],
    pattern: '/classes/:id',
    tokens: [{"old":"/classes/:id","type":0,"val":"classes","end":""},{"old":"/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['classes.update']['types'],
  },
  'classes.destroy': {
    methods: ["DELETE"],
    pattern: '/classes/:id',
    tokens: [{"old":"/classes/:id","type":0,"val":"classes","end":""},{"old":"/classes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['classes.destroy']['types'],
  },
  'classes.addStudent': {
    methods: ["POST"],
    pattern: '/classes/:id/students',
    tokens: [{"old":"/classes/:id/students","type":0,"val":"classes","end":""},{"old":"/classes/:id/students","type":1,"val":"id","end":""},{"old":"/classes/:id/students","type":0,"val":"students","end":""}],
    types: placeholder as Registry['classes.addStudent']['types'],
  },
  'classes.updateStudent': {
    methods: ["PUT"],
    pattern: '/classes/:id/students/:studentId',
    tokens: [{"old":"/classes/:id/students/:studentId","type":0,"val":"classes","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"id","end":""},{"old":"/classes/:id/students/:studentId","type":0,"val":"students","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"studentId","end":""}],
    types: placeholder as Registry['classes.updateStudent']['types'],
  },
  'classes.removeStudent': {
    methods: ["DELETE"],
    pattern: '/classes/:id/students/:studentId',
    tokens: [{"old":"/classes/:id/students/:studentId","type":0,"val":"classes","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"id","end":""},{"old":"/classes/:id/students/:studentId","type":0,"val":"students","end":""},{"old":"/classes/:id/students/:studentId","type":1,"val":"studentId","end":""}],
    types: placeholder as Registry['classes.removeStudent']['types'],
  },
  'teaching-modules.index': {
    methods: ["GET","HEAD"],
    pattern: '/teaching-modules',
    tokens: [{"old":"/teaching-modules","type":0,"val":"teaching-modules","end":""}],
    types: placeholder as Registry['teaching-modules.index']['types'],
  },
  'teaching-modules.store': {
    methods: ["POST"],
    pattern: '/teaching-modules',
    tokens: [{"old":"/teaching-modules","type":0,"val":"teaching-modules","end":""}],
    types: placeholder as Registry['teaching-modules.store']['types'],
  },
  'teaching-modules.show': {
    methods: ["GET","HEAD"],
    pattern: '/teaching-modules/:id',
    tokens: [{"old":"/teaching-modules/:id","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['teaching-modules.show']['types'],
  },
  'teaching-modules.update': {
    methods: ["PUT"],
    pattern: '/teaching-modules/:id',
    tokens: [{"old":"/teaching-modules/:id","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['teaching-modules.update']['types'],
  },
  'teaching-modules.destroy': {
    methods: ["DELETE"],
    pattern: '/teaching-modules/:id',
    tokens: [{"old":"/teaching-modules/:id","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['teaching-modules.destroy']['types'],
  },
  'teaching-modules.generate': {
    methods: ["POST"],
    pattern: '/teaching-modules/generate',
    tokens: [{"old":"/teaching-modules/generate","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['teaching-modules.generate']['types'],
  },
  'teaching-modules.export': {
    methods: ["GET","HEAD"],
    pattern: '/teaching-modules/:id/export',
    tokens: [{"old":"/teaching-modules/:id/export","type":0,"val":"teaching-modules","end":""},{"old":"/teaching-modules/:id/export","type":1,"val":"id","end":""},{"old":"/teaching-modules/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['teaching-modules.export']['types'],
  },
  'exams.index': {
    methods: ["GET","HEAD"],
    pattern: '/exams',
    tokens: [{"old":"/exams","type":0,"val":"exams","end":""}],
    types: placeholder as Registry['exams.index']['types'],
  },
  'exams.store': {
    methods: ["POST"],
    pattern: '/exams',
    tokens: [{"old":"/exams","type":0,"val":"exams","end":""}],
    types: placeholder as Registry['exams.store']['types'],
  },
  'exams.show': {
    methods: ["GET","HEAD"],
    pattern: '/exams/:id',
    tokens: [{"old":"/exams/:id","type":0,"val":"exams","end":""},{"old":"/exams/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['exams.show']['types'],
  },
  'exams.update': {
    methods: ["PUT"],
    pattern: '/exams/:id',
    tokens: [{"old":"/exams/:id","type":0,"val":"exams","end":""},{"old":"/exams/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['exams.update']['types'],
  },
  'exams.destroy': {
    methods: ["DELETE"],
    pattern: '/exams/:id',
    tokens: [{"old":"/exams/:id","type":0,"val":"exams","end":""},{"old":"/exams/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['exams.destroy']['types'],
  },
  'exams.generate': {
    methods: ["POST"],
    pattern: '/exams/generate',
    tokens: [{"old":"/exams/generate","type":0,"val":"exams","end":""},{"old":"/exams/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['exams.generate']['types'],
  },
  'exams.export': {
    methods: ["GET","HEAD"],
    pattern: '/exams/:id/export',
    tokens: [{"old":"/exams/:id/export","type":0,"val":"exams","end":""},{"old":"/exams/:id/export","type":1,"val":"id","end":""},{"old":"/exams/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['exams.export']['types'],
  },
  'annual-plans.index': {
    methods: ["GET","HEAD"],
    pattern: '/annual-plans',
    tokens: [{"old":"/annual-plans","type":0,"val":"annual-plans","end":""}],
    types: placeholder as Registry['annual-plans.index']['types'],
  },
  'annual-plans.store': {
    methods: ["POST"],
    pattern: '/annual-plans',
    tokens: [{"old":"/annual-plans","type":0,"val":"annual-plans","end":""}],
    types: placeholder as Registry['annual-plans.store']['types'],
  },
  'annual-plans.show': {
    methods: ["GET","HEAD"],
    pattern: '/annual-plans/:id',
    tokens: [{"old":"/annual-plans/:id","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annual-plans.show']['types'],
  },
  'annual-plans.update': {
    methods: ["PUT"],
    pattern: '/annual-plans/:id',
    tokens: [{"old":"/annual-plans/:id","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annual-plans.update']['types'],
  },
  'annual-plans.destroy': {
    methods: ["DELETE"],
    pattern: '/annual-plans/:id',
    tokens: [{"old":"/annual-plans/:id","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['annual-plans.destroy']['types'],
  },
  'annual-plans.generate': {
    methods: ["POST"],
    pattern: '/annual-plans/generate',
    tokens: [{"old":"/annual-plans/generate","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['annual-plans.generate']['types'],
  },
  'annual-plans.export': {
    methods: ["GET","HEAD"],
    pattern: '/annual-plans/:id/export',
    tokens: [{"old":"/annual-plans/:id/export","type":0,"val":"annual-plans","end":""},{"old":"/annual-plans/:id/export","type":1,"val":"id","end":""},{"old":"/annual-plans/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['annual-plans.export']['types'],
  },
  'semester-plans.index': {
    methods: ["GET","HEAD"],
    pattern: '/semester-plans',
    tokens: [{"old":"/semester-plans","type":0,"val":"semester-plans","end":""}],
    types: placeholder as Registry['semester-plans.index']['types'],
  },
  'semester-plans.store': {
    methods: ["POST"],
    pattern: '/semester-plans',
    tokens: [{"old":"/semester-plans","type":0,"val":"semester-plans","end":""}],
    types: placeholder as Registry['semester-plans.store']['types'],
  },
  'semester-plans.show': {
    methods: ["GET","HEAD"],
    pattern: '/semester-plans/:id',
    tokens: [{"old":"/semester-plans/:id","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['semester-plans.show']['types'],
  },
  'semester-plans.update': {
    methods: ["PUT"],
    pattern: '/semester-plans/:id',
    tokens: [{"old":"/semester-plans/:id","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['semester-plans.update']['types'],
  },
  'semester-plans.destroy': {
    methods: ["DELETE"],
    pattern: '/semester-plans/:id',
    tokens: [{"old":"/semester-plans/:id","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['semester-plans.destroy']['types'],
  },
  'semester-plans.generate': {
    methods: ["POST"],
    pattern: '/semester-plans/generate',
    tokens: [{"old":"/semester-plans/generate","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['semester-plans.generate']['types'],
  },
  'semester-plans.export': {
    methods: ["GET","HEAD"],
    pattern: '/semester-plans/:id/export',
    tokens: [{"old":"/semester-plans/:id/export","type":0,"val":"semester-plans","end":""},{"old":"/semester-plans/:id/export","type":1,"val":"id","end":""},{"old":"/semester-plans/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['semester-plans.export']['types'],
  },
  'rppm.index': {
    methods: ["GET","HEAD"],
    pattern: '/rppm',
    tokens: [{"old":"/rppm","type":0,"val":"rppm","end":""}],
    types: placeholder as Registry['rppm.index']['types'],
  },
  'rppm.show': {
    methods: ["GET","HEAD"],
    pattern: '/rppm/:id',
    tokens: [{"old":"/rppm/:id","type":0,"val":"rppm","end":""},{"old":"/rppm/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rppm.show']['types'],
  },
  'rppm.update': {
    methods: ["PUT"],
    pattern: '/rppm/:id',
    tokens: [{"old":"/rppm/:id","type":0,"val":"rppm","end":""},{"old":"/rppm/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rppm.update']['types'],
  },
  'rppm.destroy': {
    methods: ["DELETE"],
    pattern: '/rppm/:id',
    tokens: [{"old":"/rppm/:id","type":0,"val":"rppm","end":""},{"old":"/rppm/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rppm.destroy']['types'],
  },
  'rppm.generate': {
    methods: ["POST"],
    pattern: '/rppm/generate',
    tokens: [{"old":"/rppm/generate","type":0,"val":"rppm","end":""},{"old":"/rppm/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['rppm.generate']['types'],
  },
  'rpph.index': {
    methods: ["GET","HEAD"],
    pattern: '/rpph',
    tokens: [{"old":"/rpph","type":0,"val":"rpph","end":""}],
    types: placeholder as Registry['rpph.index']['types'],
  },
  'rpph.show': {
    methods: ["GET","HEAD"],
    pattern: '/rpph/:id',
    tokens: [{"old":"/rpph/:id","type":0,"val":"rpph","end":""},{"old":"/rpph/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rpph.show']['types'],
  },
  'rpph.update': {
    methods: ["PUT"],
    pattern: '/rpph/:id',
    tokens: [{"old":"/rpph/:id","type":0,"val":"rpph","end":""},{"old":"/rpph/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rpph.update']['types'],
  },
  'rpph.destroy': {
    methods: ["DELETE"],
    pattern: '/rpph/:id',
    tokens: [{"old":"/rpph/:id","type":0,"val":"rpph","end":""},{"old":"/rpph/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rpph.destroy']['types'],
  },
  'rpph.generate': {
    methods: ["POST"],
    pattern: '/rpph/generate',
    tokens: [{"old":"/rpph/generate","type":0,"val":"rpph","end":""},{"old":"/rpph/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['rpph.generate']['types'],
  },
  'paud-assessments.index': {
    methods: ["GET","HEAD"],
    pattern: '/paud-assessments',
    tokens: [{"old":"/paud-assessments","type":0,"val":"paud-assessments","end":""}],
    types: placeholder as Registry['paud-assessments.index']['types'],
  },
  'paud-assessments.store': {
    methods: ["POST"],
    pattern: '/paud-assessments',
    tokens: [{"old":"/paud-assessments","type":0,"val":"paud-assessments","end":""}],
    types: placeholder as Registry['paud-assessments.store']['types'],
  },
  'paud-assessments.update': {
    methods: ["PUT"],
    pattern: '/paud-assessments/:id',
    tokens: [{"old":"/paud-assessments/:id","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['paud-assessments.update']['types'],
  },
  'paud-assessments.destroy': {
    methods: ["DELETE"],
    pattern: '/paud-assessments/:id',
    tokens: [{"old":"/paud-assessments/:id","type":0,"val":"paud-assessments","end":""},{"old":"/paud-assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['paud-assessments.destroy']['types'],
  },
  'assessments.index': {
    methods: ["GET","HEAD"],
    pattern: '/assessments',
    tokens: [{"old":"/assessments","type":0,"val":"assessments","end":""}],
    types: placeholder as Registry['assessments.index']['types'],
  },
  'assessments.store': {
    methods: ["POST"],
    pattern: '/assessments',
    tokens: [{"old":"/assessments","type":0,"val":"assessments","end":""}],
    types: placeholder as Registry['assessments.store']['types'],
  },
  'assessments.show': {
    methods: ["GET","HEAD"],
    pattern: '/assessments/:id',
    tokens: [{"old":"/assessments/:id","type":0,"val":"assessments","end":""},{"old":"/assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['assessments.show']['types'],
  },
  'assessments.updateScores': {
    methods: ["PUT"],
    pattern: '/assessments/:id/scores',
    tokens: [{"old":"/assessments/:id/scores","type":0,"val":"assessments","end":""},{"old":"/assessments/:id/scores","type":1,"val":"id","end":""},{"old":"/assessments/:id/scores","type":0,"val":"scores","end":""}],
    types: placeholder as Registry['assessments.updateScores']['types'],
  },
  'assessments.destroy': {
    methods: ["DELETE"],
    pattern: '/assessments/:id',
    tokens: [{"old":"/assessments/:id","type":0,"val":"assessments","end":""},{"old":"/assessments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['assessments.destroy']['types'],
  },
  'assessments.export': {
    methods: ["GET","HEAD"],
    pattern: '/assessments/:id/export',
    tokens: [{"old":"/assessments/:id/export","type":0,"val":"assessments","end":""},{"old":"/assessments/:id/export","type":1,"val":"id","end":""},{"old":"/assessments/:id/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['assessments.export']['types'],
  },
  'subjects.index': {
    methods: ["GET","HEAD"],
    pattern: '/subjects',
    tokens: [{"old":"/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['subjects.index']['types'],
  },
  'subjects.store': {
    methods: ["POST"],
    pattern: '/subjects',
    tokens: [{"old":"/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['subjects.store']['types'],
  },
  'subjects.storeDefaults': {
    methods: ["POST"],
    pattern: '/subjects/defaults',
    tokens: [{"old":"/subjects/defaults","type":0,"val":"subjects","end":""},{"old":"/subjects/defaults","type":0,"val":"defaults","end":""}],
    types: placeholder as Registry['subjects.storeDefaults']['types'],
  },
  'subjects.update': {
    methods: ["PUT"],
    pattern: '/subjects/:id',
    tokens: [{"old":"/subjects/:id","type":0,"val":"subjects","end":""},{"old":"/subjects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['subjects.update']['types'],
  },
  'subjects.destroy': {
    methods: ["DELETE"],
    pattern: '/subjects/:id',
    tokens: [{"old":"/subjects/:id","type":0,"val":"subjects","end":""},{"old":"/subjects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['subjects.destroy']['types'],
  },
  'settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.index']['types'],
  },
  'settings.update': {
    methods: ["PUT"],
    pattern: '/settings',
    tokens: [{"old":"/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.update']['types'],
  },
  'admin.users.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.index']['types'],
  },
  'admin.users.update': {
    methods: ["PUT"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.update']['types'],
  },
  'admin.users.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.destroy']['types'],
  },
  'admin.packages.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/packages',
    tokens: [{"old":"/admin/packages","type":0,"val":"admin","end":""},{"old":"/admin/packages","type":0,"val":"packages","end":""}],
    types: placeholder as Registry['admin.packages.index']['types'],
  },
  'admin.packages.store': {
    methods: ["POST"],
    pattern: '/admin/packages',
    tokens: [{"old":"/admin/packages","type":0,"val":"admin","end":""},{"old":"/admin/packages","type":0,"val":"packages","end":""}],
    types: placeholder as Registry['admin.packages.store']['types'],
  },
  'admin.packages.update': {
    methods: ["PUT"],
    pattern: '/admin/packages/:id',
    tokens: [{"old":"/admin/packages/:id","type":0,"val":"admin","end":""},{"old":"/admin/packages/:id","type":0,"val":"packages","end":""},{"old":"/admin/packages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.packages.update']['types'],
  },
  'admin.packages.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/packages/:id',
    tokens: [{"old":"/admin/packages/:id","type":0,"val":"admin","end":""},{"old":"/admin/packages/:id","type":0,"val":"packages","end":""},{"old":"/admin/packages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.packages.destroy']['types'],
  },
  'admin.academic-years.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/academic-years',
    tokens: [{"old":"/admin/academic-years","type":0,"val":"admin","end":""},{"old":"/admin/academic-years","type":0,"val":"academic-years","end":""}],
    types: placeholder as Registry['admin.academic-years.index']['types'],
  },
  'admin.academic-years.store': {
    methods: ["POST"],
    pattern: '/admin/academic-years',
    tokens: [{"old":"/admin/academic-years","type":0,"val":"admin","end":""},{"old":"/admin/academic-years","type":0,"val":"academic-years","end":""}],
    types: placeholder as Registry['admin.academic-years.store']['types'],
  },
  'admin.academic-years.update': {
    methods: ["PUT"],
    pattern: '/admin/academic-years/:id',
    tokens: [{"old":"/admin/academic-years/:id","type":0,"val":"admin","end":""},{"old":"/admin/academic-years/:id","type":0,"val":"academic-years","end":""},{"old":"/admin/academic-years/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.academic-years.update']['types'],
  },
  'admin.academic-years.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/academic-years/:id',
    tokens: [{"old":"/admin/academic-years/:id","type":0,"val":"admin","end":""},{"old":"/admin/academic-years/:id","type":0,"val":"academic-years","end":""},{"old":"/admin/academic-years/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.academic-years.destroy']['types'],
  },
  'admin.ai-settings.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/ai-settings',
    tokens: [{"old":"/admin/ai-settings","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings","type":0,"val":"ai-settings","end":""}],
    types: placeholder as Registry['admin.ai-settings.index']['types'],
  },
  'admin.ai-settings.update': {
    methods: ["PUT"],
    pattern: '/admin/ai-settings',
    tokens: [{"old":"/admin/ai-settings","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings","type":0,"val":"ai-settings","end":""}],
    types: placeholder as Registry['admin.ai-settings.update']['types'],
  },
  'admin.ai-settings.test': {
    methods: ["POST"],
    pattern: '/admin/ai-settings/test',
    tokens: [{"old":"/admin/ai-settings/test","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings/test","type":0,"val":"ai-settings","end":""},{"old":"/admin/ai-settings/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['admin.ai-settings.test']['types'],
  },
  'admin.ai-settings.models': {
    methods: ["POST"],
    pattern: '/admin/ai-settings/models',
    tokens: [{"old":"/admin/ai-settings/models","type":0,"val":"admin","end":""},{"old":"/admin/ai-settings/models","type":0,"val":"ai-settings","end":""},{"old":"/admin/ai-settings/models","type":0,"val":"models","end":""}],
    types: placeholder as Registry['admin.ai-settings.models']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
